from . import res_country
from . import sale_order
from . import sale_order_line
from . import res_partner
from . import fastapi_endpoint
from . import stock_picking
from . import product_product
from . import alc_b2c_client
from . import ir_rule
