# -*- coding: utf-8 -*-
# Copyright 2021 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Alcyon E-Shop Application",
    "description": """Install all apps and modules required by the E-Shop""",
    "version": "10.0.1.0.2",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        "alc_price_cache_exclusive",
        "alc_elasticsearch_price_sorting",
        "alc_eshop",
        "alc_eshop_api_v2",
        "alc_eshop_ads",
        "alc_eshop_cms",
        "alc_eshop_form",
        "alc_eshop_info_banner",
        "alc_documents_eshop_services",
        "alc_eshop_classifieds_service",
        "alc_eshop_models_url",
        "alc_eshop_product_domain",
        "alc_eshop_partner_veterinary",
        "alc_eshop_product_category_sequence",
        "alc_eshop_product_expiry",
        "alc_eshop_product_on_order",
        "alc_eshop_product_promotion_subscription",
        "alc_eshop_product_stock",
        "alc_eshop_sale_statistic",
        "alc_eshop_sale_triple_discount",
        "alc_eshop_services_orders_suite_channel",
        "alc_eshop_salesperson",
        "alc_eshop_veterinary_group",
        "alc_registration_eshop_service",
        "alc_keycloak",
        "alc_elasticsearch_security_vt_groups",
        "alc_product_promotion_mailing",
        "alc_sale_cart_price_recalculation",
        "alc_search_engine",
        "shopinvader_assortment_bind",
        "shopinvader_search_engine_update_image",
        "shopinvader_search_engine_update_media",
        "shopinvader_search_engine_update_specials",
        "shopinvader_search_engine_update_vtgroups",
        "alc_magento_api",
    ],
    "application": True,
    "data": [
        "security/res_groups.xml",
        "security/acl_veterinary_group.xml",
        "security/alc_shopinvader_backend.xml",
        "security/rule+acl_alc_document.xml",
        "security/rule+acl_alc_product_promotion_subscription.xml",
        "security/rule+acl_product_product.xml",
        "security/rule+acl_res_partner.xml",
        "security/rule+acl_alc_classifieds.xml",
        "security/rule+acl_alc_eshop_form.xml",
        "security/rule+acl_alc_eshop_product_on_order.xml",
        "security/rule+acl_alc_eshop_product_ordered_qty.xml",
        "security/rule+acl_sale_order.xml",
        "security/rule+acl_sale_order_line.xml",
        "security/rule_storage_file.xml",
        "data/res_users.xml",
        "data/auth_jwt_validator.xml",
        "data/shopinvader_backend.xml",
        "data/ir_export_product.xml",
        "views/eshop_app_menu.xml",
    ],
    "demo": [],
    "post_init_hook": "post_init_hook",
    "external_dependencies": {"python": ["openupgradelib"]},
}
