#!/usr/bin/env python3
import os
import subprocess
import sys
import time


def check_call(cmd):
    print(" ".join(cmd))
    sys.stdout.flush()
    subprocess.check_call(cmd)


db_name = os.getenv("DB_NAME")
db_base = os.getenv("DB_BASE")

if db_name:
    for database in db_name.split(","):
        if db_base:
            check_call(
                [
                    "click-odoo-copydb",
                    "--force-disconnect",
                    "--if-source-exists",
                    "--unless-dest-exists",
                    db_base,
                    database,
                ]
            )
        check_call(
            [
                "click-odoo-update",
                "--if-exists",
                "-d",
                database,
                "--i18n-overwrite",
                "--ignore-core-addons",
            ]
        )
        check_call(
            [
                "click-odoo-initdb",
                "--unless-exists",
                "-n",
                database,
                # "-m",
                # TODO "alc_all,alc_all_enterprise",
            ]
        )

while subprocess.call(["wkhtmltopdf", "--version"]) != 0:
    print("Waiting for wkhtmltopdf...")
    time.sleep(10)
