---
apiVersion: v1
kind: Service
metadata:
  name: {{CI_ENVIRONMENT_SLUG}}
  labels:
    app: {{CI_ENVIRONMENT_SLUG}}
spec:
  type: ClusterIP
  ports:
    - port: 8069
      targetPort: 8069
      protocol: TCP
      name: web
    - port: 8072
      targetPort: 8072
      protocol: TCP
      name: longpolling
  selector:
    app: {{CI_ENVIRONMENT_SLUG}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{CI_ENVIRONMENT_SLUG}}
  labels:
    app: {{CI_ENVIRONMENT_SLUG}}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: {{CI_ENVIRONMENT_SLUG}}
  template:
    metadata:
      labels:
        app: {{CI_ENVIRONMENT_SLUG}}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{CI_ENVIRONMENT_SLUG}}
          image: "{{ IMAGE }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: "odoo-data"
              mountPath: "/data/odoo"
          env:
            - name: RUNNING_ENV
              value: "test"
            - name: KWKHTMLTOPDF_SERVER_URL
              value: "http://kwkhtmltopdf.default"
            - name: DB_NAME
              value: "{{ TEST_DB_NAME }}"
            - name: DB_FILTER
              value: "{{ TEST_DB_FILTER }}"
            - name: DB_HOST
              value: "{{ TEST_DB_HOST }}"
            - name: DB_USER
              value: "{{ TEST_DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ TEST_DB_PASSWORD }}"
            - name: LIST_DB
              value: "True"
            - name: LOG_LEVEL
              value: "debug"
            - name: MAX_CRON_THREADS
              value: "1"
            - name: SERVER_WIDE_MODULES
              value: "base_geoengine,web,queue_job"
            - name: ADMIN_PASSWD
              value: "{{ TEST_ADMIN_PASSWD }}"
            - name: LIMIT_TIME_CPU
              value: "900"
            - name: LIMIT_TIME_REAL
              value: "1800"
            - name: UNACCENT
              value: "True"
            - name: ADDITIONAL_ODOO_RC
              value: |
                [api_key_chronovet_rest_api]
                user=alc_b2c_rest_api_user
                key= {{ TEST_CHRONOVET_API_KEY }}
                backend_name=Chronovet
          ports:
            - name: web
              containerPort: 8069
            - name: longpolling
              containerPort: 8072
          readinessProbe:
            httpGet:
              path: /
              port: 8069
            initialDelaySeconds: 5
            timeoutSeconds: 180
          resources:
            requests:
              memory: 2000Mi
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{CI_ENVIRONMENT_SLUG}}
  labels:
    app: {{CI_ENVIRONMENT_SLUG}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  tls:
    - hosts:
        - '{{ CI_ENVIRONMENT_URL | replace("https://", "") | replace("http://", "")}}'
  rules:
    - host: '{{ CI_ENVIRONMENT_URL | replace("https://", "") | replace("http://", "")}}'
      http:
        paths:
          - path: /
            backend:
              serviceName: {{CI_ENVIRONMENT_SLUG}}
              servicePort: 8069
          - path: /longpolling
            backend:
              serviceName: {{CI_ENVIRONMENT_SLUG}}
              servicePort: 8072
