#!/bin/bash
#
# Check validy of given environment variables
# DB2IMPORT_MODE: history/final_update
# DB2IMPORT_YEARS: positive integer
# DB2IMPORT_MONTHS: positive integer
# DB2IMPORT_10CLI: truely of falsy string
# DB2IMPORT_10CLI_YEARS: positive integer
# DB2IMPORT_10CLI_MONTHS: positive integer

if [ -n "$DB2IMPORT_MODE" ] ; then
    if [ "$DB2IMPORT_MODE" != "history" -a "$DB2IMPORT_MODE" != "final_update" ] ; then
        echo -e "\033[0:31mERROR\033[0m: DB2IMPORT_MODE value '$DB2IMPORT_MODE' is not valid"
        echo -e "       must be 'history' or 'final_update'"
        exit 1
    fi
fi
if [ -n "$DB2IMPORT_10CLI" ] ; then
    if [ "$DB2IMPORT_10CLI" != "False" -o "$DB2IMPORT_10CLI" != "no" -o "$DB2IMPORT_10CLI" != "True" -o "$DB2IMPORT_10CLI" != "yes" ] ; then
        echo -e "\033[0:31mERROR\033[0m: DB2IMPORT_10CLI value '$DB2IMPORT_10CLI' is not valid"
        echo -e "       must be 'True', 'False, 'yes' or 'no'"
        exit 1
    fi
fi

re='^[0-9]+$'

if [ -n "$DB2IMPORT_YEARS" ] ; then
    if ! [[ "$DB2IMPORT_YEARS" =~ $re ]] ; then
        echo -e "\033[0:31mERROR\033[0m: DB2IMPORT_YEARS value '$DB2IMPORT_YEARS' is not valid"
        echo -e "       must be a positive integer"
        exit 1
    fi
fi
if [ -n "$DB2IMPORT_MONTHS" ] ; then
    if ! [[ "$DB2IMPORT_MONTHS" =~ $re ]] ; then
        echo -e "\033[0:31mERROR\033[0m: DB2IMPORT_MONTHS value '$DB2IMPORT_MONTHS' is not valid"
        echo -e "       must be a positive integer"
        exit 1
    fi
fi
if [ -n "$DB2IMPORT_10CLI_YEARS" ] ; then
    if ! [[ "$DB2IMPORT_10CLI_YEARS" =~ $re ]] ; then
        echo -e "\033[0:31mERROR\033[0m: DB2IMPORT_10CLI_YEARS value '$DB2IMPORT_10CLI_YEARS' is not valid"
        echo -e "       must be a positive integer"
        exit 1
    fi
fi
if [ -n "$DB2IMPORT_10CLI_MONTHS" ] ; then
    if ! [[ "$DB2IMPORT_10CLI_MONTHS" =~ $re ]] ; then
        echo -e "\033[0:31mERROR\033[0m: DB2IMPORT_10CLI_MONTHS value '$DB2IMPORT_10CLI_MONTHS' is not valid"
        echo -e "       must be a positive integer"
        exit 1
    fi
fi
