# -*- coding: utf-8 -*-
from . import zetes_test_classes
from . import test_domain_interface
from . import test_assignment
from . import test_assignment_parking
from . import test_assignment_reserve
from . import test_catchweight
from . import test_catchweight_parking
from . import test_catchweight_reserve
from . import test_itempick
from . import test_location
from . import test_print
from . import test_refdata
from . import test_usercontext
from . import test_exceptions
from . import test_interruption
from . import test_itemmove_parking
from . import test_itemmove_reserve
from . import test_full
from . import test_full_parking
from . import test_full_reserve
from . import test_savepoint
