CREATE OR REPLACE VIEW zelapro_export_products AS
  SELECT
    product.default_code AS GESART,
    template.name AS GESDEM,
    product.weight AS GESPBR,
    '' AS GESPNT,
    '' AS GESVOL,
    supplier.ref AS GESFOU,
    '' AS GESCDE,
    '' AS LIBCDE,
    '' AS GESDOU,
    '' AS GESCRF,
    '' AS GESUNA,
    purchase_uom.name AS LIBUNA,
    1 AS GESCOA,
    1 AS GESNBP,
    supplierinfo.delay AS GESDEL,
    '' AS GESECS,
    '' AS GESBPV,
    '' AS GESUNV,
    sale_uom.name AS LIBUNV,
    1 AS GESCOV,
    '' AS GESCGE,
    '' AS LIBCGE,
    '' AS GESHIS,
    '' AS LIBHIS,
    '' AS GESMCO,
    '' AS LIBCMO,
    '' AS GESETI,
    '' AS LIBETI,
    '' AS GESCGR,
    '' AS LIBCGR,
    '' AS GESCSG,
    '' AS LIBCSG,
    '' AS GESCTV,
    '' AS LIBCTV,
    '' AS GESCVA,
    '' AS GESCVV,
    '' AS GESCAN,
    '' AS GESCAV,
    '' AS GESCSA,
    template.tracking AS LIBCSA,
    '' AS GESCRE,
    '' AS LIBCRE,
    '' AS GESCHR,
    '' AS LIBCHR,
    (SELECT ir_property.value_float
     FROM ir_property
     WHERE ir_property.res_id = 'product.product,' || product.id) AS GESPAB,
    supplierinfo.price AS GESPAN,
    '' AS GESPRR,
    template.list_price AS GESPVR,
    '' AS GESPRM,
    '' AS GESPMC,
    to_char(product.create_date, 'DD/MM/YYYY') AS DATE_CREATION,
    to_char(product.write_date, 'DD/MM/YYYY') AS DATE_MODIFICATION,
    '' AS GESSOC,
    '' AS GESARC,
    '' AS GESPV2,
    '' AS GESDON,
    '' AS GESSUR,
    '' AS GESSUN,
    '' AS GESSUP,
    '' AS CPLZ03,
    '' AS CPLZ13,
    '' AS LIBZ13,
    '' AS CPLZ14,
    '' AS LIBZ14,
    '' AS CPLZ25,
    '' AS CPLZ20,
    '' AS CPLZ21,
    '' AS CPLZ24,
    '' AS CPLZ29,
    template.unit_in_box AS CPLZ30,
    '' AS CPLZ18,
    '' AS CPLZ19,
    '' AS CPLZ22,
    '' AS CPLZ23,
    '' AS CPLZ28,
    '' AS CP2Z01,
    template.unit_in_box AS CP2Z02,
    '' AS CP2Z03,
    template.unit_in_crate AS CP2Z04,
    '' AS CP2Z05,
    '' AS CP2Z06,
    '' AS CP2Z08,
    '' AS CP2Z09,
    '' AS CP2Z10,
    '' AS CP2Z11,
    '' AS CP2Z12,
    '' AS CP2Z13,
    '' AS CP2Z14,
    '' AS CP2Z15,
    '' AS CP2Z16,
    '' AS CP2Z17,
    '' AS LIBZ17,
    '' AS CP2Z18,
    '' AS LIBZ18,
    '' AS CP2Z19,
    '' AS LIBZ19,
    '' AS CP2Z20,
    '' AS CP2Z21,
    '' AS LIBZ21,
    product_add.default_code AS CP2Z22,
    product_add_rel.quantity AS CP2Z23,
    product_add_rel.quantity AS CP2Z24,
    abc.code AS ABCCOD,
    product.turnover AS ABCVAV,
    product.turnover_average AS ABCPCV,
    product.turnover_nbr_lines AS ABCNLI,
    product.turnover_average_nbr_lines AS ABCPLI,
    '' AS ABCPSE,
    product.create_date AS create_date
  FROM product_product AS product
    INNER JOIN product_template AS template ON product.product_tmpl_id = template.id
    LEFT JOIN product_uom AS purchase_uom ON template.uom_po_id = purchase_uom.id
    LEFT JOIN product_uom AS sale_uom ON template.uom_id = sale_uom.id
    LEFT JOIN product_supplierinfo AS supplierinfo ON supplierinfo.id = (SELECT min(id) FROM product_supplierinfo WHERE product_tmpl_id = template.id)
    LEFT JOIN res_partner AS supplier ON supplierinfo.name = supplier.id
    LEFT JOIN product_template_additional AS product_add_rel ON product_add_rel.id = (SELECT min(id) FROM product_template_additional WHERE original_product_id = template.id)
    LEFT JOIN product_template AS product_add ON product_add_rel.product_id = product_add.id
    LEFT JOIN activity_based_costing AS abc ON product.abc_id = abc.id
    LEFT JOIN product_category AS bu ON product.business_unit_id = bu.id;
