stages:
  - build
  - test
  - deploy

image: ghcr.io/acsone/odoo-ci-image:v20210526.0

before_script:
  - |
    function start_ssh_agent {
        eval $(ssh-agent -s)
        ssh-add <(echo "$SSH_DEPLOY_KEY")
    }
    function makepot {
        # if you use weblate, remove --msgmerge here and install the msgmerge addon on weblate
        venv/bin/click-odoo-makepot -c odoo-ci.cfg -d ${DB_NAME} --commit --msgmerge --addons-dir=$(pwd)/odoo/addons
        git push "git@gitlab.acsone.eu:${CI_PROJECT_PATH}" "HEAD:${CI_COMMIT_REF_NAME}"
    }

variables:
  PYTHON: python2.7

# lint

pre-commit:
  stage: test
  cache:
    key: pre-commit
    paths:
      - .pre-commit
  variables:
    KUBERNETES_MEMORY_REQUEST: 3500Mi
    KUBERNETES_MEMORY_LIMIT: 3500Mi
  script:
    - pipx install pre-commit
    - PRE_COMMIT_HOME=$PWD/.pre-commit pre-commit run --all-files --show-diff-on-failure
  needs: []
  interruptible: true

# build wheels

build:
  stage: build
  # use odoo-10.0 runner so we have the pre-cloned odoo
  # except for that optimization, we don't need odoo dependencies for this job
  tags:
    - git-autoshare
    - pip-cache
  script:
    - start_ssh_agent
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip wheel --no-deps -r requirements.txt --wheel-dir=release
    - venv/bin/pip wheel --no-deps -e . --wheel-dir=release-project
  artifacts:
    expire_in: 1 week
    paths:
      - release/
      - release-project/
    name: "${CI_PROJECT_NAME}-${CI_JOB_ID}-build"
  interruptible: true

# tests

.test_common:
  stage: test
  tags:
    - speedy
    - postgres
  needs:
    - job: build
      artifacts: true
  variables:
    DB_NAME: "${CI_PROJECT_NAME}-${CI_JOB_ID}"
  after_script:
    - dropdb --if-exists ${DB_NAME}
  interruptible: true
  artifacts:
    expire_in: 1 day
    paths:
      - .coverage.*
    name: "${CI_PROJECT_NAME}-${CI_JOB_ID}-coverage"

licence_check:
  extends: .test_common
  script:
    - virtualenv --python=$PYTHON venv
    # use --no-index (but not --no-deps) so missing dependencies that would not be in *.whl are detected
    - venv/bin/pip install --no-index release*/*.whl
    - manifestoo -d odoo/addons --addons-path-python=venv/bin/python check-licenses
  allow_failure: true

test-impacted:
  extends: .test_common
  variables:
    GIT_FETCH_EXTRA_FLAGS: "master:master"
  script:
    - pipx install acsoo # for checklog
    - pipx install manifestoo # up to date with list-codepends
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install --no-deps -r requirements-tests.txt # test dependencies
    - venv/bin/pip install --no-deps --no-index release/*.whl # runtime dependencies
    - venv/bin/pip install --no-deps -e .
    - MODIFIED_ADDONS=$(git diff --name-only master... | grep "odoo/addons" | sed 's/odoo.addons.//' | sed 's/\/.*//' | uniq | tr '\n' ',') || true
    - if [[ -z "$MODIFIED_ADDONS" ]] ; then echo "No changes to test."; exit 0; fi
    - MODIFIED_ADDONS=${MODIFIED_ADDONS%?} # remove trailing comma
    - echo $MODIFIED_ADDONS
    - IMPACTED_ADDONS=$(manifestoo --addons-path-python venv/bin/python --select $MODIFIED_ADDONS list-codepends --separator=,)
    - ADDONS_TEST=$(sed 's/\(alc.\?_all\|server_environment_files\|alc_product_is_new\|alc_product_barcode_required\|alc_stock_receive_lot_missing_product_nouveaute_info\),\?//g' <<<
      "$IMPACTED_ADDONS")
    - echo $ADDONS_TEST
    - ADDONS_TEST=$(sed 's/\(test_\)\{0,1\}alc_shopfloor[^,]*\(,\|$\)//g' <<< "$ADDONS_TEST");
    - ADDONS_TEST=$(sed 's/,$//' <<< "$ADDONS_TEST"); # remove trailing comma if any
    - echo $ADDONS_TEST
    - ADDONS_INIT=$(manifestoo --addons-path-python venv/bin/python --select=${ADDONS_TEST} list-depends --separator=,);
    - echo Installing ${ADDONS_INIT}
    - unbuffer venv/bin/click-odoo-initdb -c odoo-ci.cfg --new-database ${DB_NAME} --cache-prefix alc -m ${ADDONS_INIT} | acsoo checklog
    - if [[ ! -z "$ADDONS_TEST" ]] ; then
    - echo Testing ${ADDONS_TEST}
    - unbuffer venv/bin/coverage run --parallel venv/bin/odoo -c odoo-ci.cfg -d ${DB_NAME} --stop-after-init --no-xmlrpc -i ${ADDONS_TEST} --test-enable | acsoo checklog
    - else
    - echo "Nothing to test."
    - fi
  only:
    - branches
  except:
    - master
  when: on_success

.test_all:
  extends: .test_common
  script:
    - pipx install acsoo # for checklog
    - start_ssh_agent # for pushing translations
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install --no-deps -r requirements-tests.txt # test dependencies
    - venv/bin/pip install --no-deps --no-index release/*.whl # runtime dependencies
    - venv/bin/pip install --no-deps -e . # the project, in editable mode so coverage sees it
    - ALL_ADDONS=$(manifestoo -d odoo/addons list --separator=,)
    - IFS=',' read -ra ADDR <<< "$ALL_ADDONS"
    - SHOPFLOOR_ADDONS=''
    - for i in "${ADDR[@]}"; do
    - if [[ $i == 'alc_shopfloor'* ]] ; then
    - SHOPFLOOR_ADDONS=$SHOPFLOOR_ADDONS$i','
    - fi
    - done
    - ADDONS_INIT=$(manifestoo -d odoo/addons --select-exclude=alc_all,alce_all,${SHOPFLOOR_ADDONS},alc_product_is_new,alc_product_barcode_required,alc_stock_receive_lot_missing_product_nouveaute_info
      list-depends --separator=,)
    - echo Installing ${ADDONS_INIT}
    - unbuffer venv/bin/click-odoo-initdb -c odoo-ci.cfg --new-database ${DB_NAME} --cache-prefix alc -m ${ADDONS_INIT} | acsoo checklog
    # do not test server_environment_files because server_environment depends on it,
    # so testing server_environment_files implies testing server_environment,
    # and the server_environment tests require a very specific server_environment_files
    - ADDONS_TEST=$(manifestoo -d odoo/addons --select-exclude
      server_environment_files,alc_all,alc_stock_pack_operation_audit,${SHOPFLOOR_ADDONS},alc_product_is_new,alc_product_barcode_required,alc_stock_receive_lot_missing_product_nouveaute_info list
      --separator=,)
    - echo Testing ${ADDONS_TEST}
    - unbuffer venv/bin/coverage run --parallel venv/bin/odoo -c odoo-ci.cfg -d ${DB_NAME} --stop-after-init --no-xmlrpc -i ${ADDONS_TEST} --test-enable | acsoo checklog
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ] ; then makepot ; fi

test-all:
  extends: .test_all
  only:
    - branches
  except:
    - master
  when: manual

test-master:
  extends: .test_all
  only:
    - master
  when: on_success

test-new-product-barcode-required:
  extends: .test_common
  script:
    - pipx install acsoo # for checklog
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install --no-deps -r requirements-tests.txt # test dependencies
    - venv/bin/pip install --no-deps --no-index release/*.whl # runtime dependencies
    - venv/bin/pip install --no-deps -e . # the project, in editable mode so coverage sees it
    - ALL_ADDONS=$(manifestoo -d odoo/addons list --separator=,)
    - IFS=',' read -ra ADDR <<< "$ALL_ADDONS"
    - ADDONS_INIT=$(manifestoo --addons-path-python=venv/bin/python --select=alc_product_is_new,alc_product_barcode_required,alc_stock_receive_lot_missing_product_nouveaute_info list-depends
      --separator=,)
    - echo Installing ${ADDONS_INIT}
    - unbuffer venv/bin/click-odoo-initdb -c odoo-ci.cfg --new-database ${DB_NAME} --cache-prefix alc-sfl -m ${ADDONS_INIT} | acsoo checklog
    # do not test server_environment_files because server_environment depends on it,
    # so testing server_environment_files implies testing server_environment,
    # and the server_environment tests require a very specific server_environment_files
    - ADDONS_TEST=$(manifestoo --addons-path-python=venv/bin/python --select=alc_product_is_new,alc_product_barcode_required,alc_stock_receive_lot_missing_product_nouveaute_info list --separator=,)
    - echo Testing ${ADDONS_TEST}
    - unbuffer venv/bin/coverage run --parallel venv/bin/odoo -c odoo-ci.cfg -d ${DB_NAME} --stop-after-init --no-xmlrpc -i ${ADDONS_TEST} --test-enable | acsoo checklog

.test_shopfloor:
  extends: .test_common
  script:
    - pipx install acsoo # for checklog
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install --no-deps -r requirements-tests.txt # test dependencies
    - venv/bin/pip install --no-deps --no-index release/*.whl # runtime dependencies
    - venv/bin/pip install --no-deps -e . # the project, in editable mode so coverage sees it
    - ALL_ADDONS=$(manifestoo -d odoo/addons list --separator=,)
    - IFS=',' read -ra ADDR <<< "$ALL_ADDONS"
    - SHOPFLOOR_ADDONS=''
    - for i in "${ADDR[@]}"; do
    - if [[ $i == 'alc_shopfloor'* ]] ; then
    - SHOPFLOOR_ADDONS=$SHOPFLOOR_ADDONS$i','
    - fi
    - done
    - ADDONS_INIT=$(manifestoo --addons-path-python=venv/bin/python --select=${SHOPFLOOR_ADDONS} list-depends --separator=,)
    - echo Installing ${ADDONS_INIT}
    - unbuffer venv/bin/click-odoo-initdb -c odoo-ci.cfg --new-database ${DB_NAME} --cache-prefix alc-sfl -m ${ADDONS_INIT} | acsoo checklog
    - ADDONS_TEST=$(manifestoo --addons-path-python=venv/bin/python --select=${SHOPFLOOR_ADDONS} list --separator=,)
    - echo Testing ${ADDONS_TEST}
    - unbuffer venv/bin/coverage run --parallel venv/bin/odoo -c odoo-ci.cfg -d ${DB_NAME} --stop-after-init --no-xmlrpc -i ${ADDONS_TEST} --test-enable | acsoo checklog

test-shopfloor-manual:
  extends: .test_shopfloor
  only:
    - branches
  except:
    - master
  when: manual

test-shopfloor-master:
  extends: .test_shopfloor
  only:
    - master
  when: on_success

test-shopfloor-branch:
  extends: .test_common
  variables:
    GIT_FETCH_EXTRA_FLAGS: "master:master"
  script:
    - pipx install acsoo # for checklog
    - pipx install manifestoo # up to date with list-codepends
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install --no-deps -r requirements-tests.txt # test dependencies
    - venv/bin/pip install --no-deps --no-index release/*.whl # runtime dependencies
    - venv/bin/pip install --no-deps -e . # the project, in editable mode so coverage sees it
    - MODIFIED_ADDONS=$(git diff --name-only master... | grep "odoo/addons" | sed 's/odoo.addons.//' | sed 's/\/.*//' | uniq | tr '\n' ',') || true # if empty, $? is 1 on gitlab, which interrupts execution.
    - if [[ -z "$MODIFIED_ADDONS" ]] ; then echo "No changes to test."; exit 0; fi
    - MODIFIED_ADDONS=${MODIFIED_ADDONS%?} # remove trailing comma
    - echo $MODIFIED_ADDONS
    - IMPACTED_ADDONS=$(manifestoo --addons-path-python venv/bin/python --select $MODIFIED_ADDONS list-codepends --separator=,)
    - ALL_ADDONS=$(manifestoo -d odoo/addons list --separator=,)
    - IFS=',' read -ra ADDR <<< "$ALL_ADDONS"
    - SHOPFLOOR_ADDONS=''
    - for i in "${ADDR[@]}"; do
    - if [[ $i == 'alc_shopfloor'* ]] ; then
    - SHOPFLOOR_ADDONS=$SHOPFLOOR_ADDONS$i','
    - fi
    - done
    - if [[ $IMPACTED_ADDONS == *alc_shopfloor* ]] ; then
    - ADDONS_INIT=$(manifestoo --addons-path-python=venv/bin/python --select=${SHOPFLOOR_ADDONS} list-depends --separator=,)
    - echo Installing ${ADDONS_INIT}
    - unbuffer venv/bin/click-odoo-initdb -c odoo-ci.cfg --new-database ${DB_NAME} --cache-prefix alc-sfl -m ${ADDONS_INIT} | acsoo checklog
    - ADDONS_TEST=$(manifestoo --addons-path-python=venv/bin/python --select=${SHOPFLOOR_ADDONS} list --separator=,)
    - echo Testing ${ADDONS_TEST}
    - unbuffer venv/bin/coverage run --parallel venv/bin/odoo -c odoo-ci.cfg -d ${DB_NAME} --stop-after-init --no-xmlrpc -i ${ADDONS_TEST} --test-enable | acsoo checklog
    - else
    - echo "Skipping Shopfloor Tests"
    - fi
  only:
    - branches
  except:
    - master
  when: on_success

coverage-report:
  stage: test
  script:
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install coverage
    - venv/bin/coverage combine
    - venv/bin/coverage html --skip-empty --show-contexts
    - venv/bin/coverage xml
    - venv/bin/coverage report --skip-empty
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    expire_in: 1 day
    paths:
      - htmlcov/
      - coverage.xml
    name: "${CI_PROJECT_NAME}-${CI_JOB_ID}-coverage-html"
    expose_as: "Test coverage"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  needs:
    - job: test-all
      artifacts: true
    - job: test-shopfloor-manual
      artifacts: true
    - job: test-new-product-barcode-required
      artifacts: true
  interruptible: true
  only:
    - branches
  except:
    - master
  when: on_success

coverage-report-master:
  stage: test
  script:
    - virtualenv --python=$PYTHON venv
    - venv/bin/pip install coverage
    - venv/bin/coverage combine
    - venv/bin/coverage html --skip-empty --show-contexts
    - venv/bin/coverage xml
    - venv/bin/coverage report --skip-empty
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    expire_in: 1 day
    paths:
      - htmlcov/
      - coverage.xml
    name: "${CI_PROJECT_NAME}-${CI_JOB_ID}-coverage-html"
    expose_as: "Test coverage"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  needs:
    - job: test-master
      artifacts: true
    - job: test-shopfloor-master
      artifacts: true
    - job: test-new-product-barcode-required
      artifacts: true
  interruptible: true
  only:
    - master
  when: on_success

# build container images

.build-and-publish-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script: []
  script:
    # https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --cache=true \
        --cache-repo=${CI_REGISTRY_IMAGE}/cache \
        --use-new-run \
        --destination ${CI_REGISTRY_IMAGE}${IMAGE_FLAVOR}:${CI_COMMIT_REF_NAME}
  needs:
    - job: build
      artifacts: true

build-image:
  extends: .build-and-publish-image
  only:
    - /^1\.93\.\d+$/

build-review-image:
  extends: .build-and-publish-image
  variables:
    IMAGE_FLAVOR: /review
  environment:
    name: review/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master
  when: manual

# deployments to acsone environments (review, test)

.deploy-trigger:
  stage: deploy
  image: ghcr.io/acsone/deploy-tools
  script:
    - echo "triggering deploy of ${CI_REGISTRY_IMAGE}${IMAGE_FLAVOR}:${CI_COMMIT_REF_NAME} to ${CI_ENVIRONMENT_SLUG}"
    - |
      curl --request POST \
        --form "token=${CI_JOB_TOKEN}" \
        --form "ref=deploy" \
        --form "variables[DEPLOY_ENV]=${CI_ENVIRONMENT_SLUG}" \
        --form "variables[DEPLOY_IMAGE]=${CI_REGISTRY_IMAGE}${IMAGE_FLAVOR}" \
        --form "variables[DEPLOY_COMMIT_REF_NAME]=${CI_COMMIT_REF_NAME}" \
        --form "variables[DEPLOY_COMMIT_SHA]=${CI_COMMIT_SHA}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"

deploy-test-trigger:
  extends: .deploy-trigger
  environment:
    name: test
  needs:
    - job: build-image
  only:
    - /^1\.93\.\d+$/

deploy-review-trigger:
  extends: .deploy-trigger
  variables:
    IMAGE_FLAVOR: /review
  environment:
    name: review/$CI_COMMIT_REF_NAME
  needs:
    - job: build-review-image
  only:
    - branches
  except:
    - master
  when: on_success # automatic after build-review-image

# deployments to customer environments (uat, preprod, prod)

.deploy-customer:
  extends: .deploy-trigger
  needs:
    - job: build-image
  only:
    - /^1\.93\.\d+$/
  when: manual

deploy-uat-trigger:
  extends: .deploy-customer
  environment:
    name: uat

deploy-preprod-trigger:
  extends: .deploy-customer
  environment:
    name: preprod

deploy-prod-trigger:
  extends: .deploy-customer
  environment:
    name: prod
