stages:
  - deploy

workflow:
  rules:
    - if: "$DEPLOY_ENV && $DEPLOY_COMMIT_REF_NAME"

variables:
  DEPLOY_COMMIT_REF_NAME:
    value: "x.y.z"
    description: The commit ref (tag or branch) to deploy.
  DEPLOY_ENV:
    value: "test|review"
    description: The environment to deploy to (test or review).

deploy-test:
  stage: deploy
  script:
    - echo "Deploying ${DEPLOY_COMMIT_REF_NAME} to ${DEPLOY_ENV}"
  environment:
    name: test
    on_stop: stop-test
  rules:
    - if: '$DEPLOY_ENV == "test"'

stop-test:
  stage: deploy
  script:
    - echo "Stopping ${DEPLOY_ENV}"
  environment:
    name: test
    action: stop
  rules:
    - if: '$DEPLOY_ENV == "test"'
      when: manual

deploy-review:
  stage: deploy
  script:
    - echo "Deploying ${DEPLOY_COMMIT_REF_NAME} to ${DEPLOY_ENV}"
  environment:
    name: review-${DEPLOY_COMMIT_REF_NAME}
    on_stop: stop-review
  rules:
    - if: '$DEPLOY_ENV == "review"'

stop-review:
  stage: deploy
  script:
    - echo "Stopping ${DEPLOY_ENV}"
  environment:
    name: review-${DEPLOY_COMMIT_REF_NAME}
    action: stop
  rules:
    - if: '$DEPLOY_ENV == "review"'
      when: manual
