exclude: |
  (?x)
  .pot$|
  ^odoo/addons/alc_b2c_connector\/utils.py|
  # NOT INSTALLABLE ADDONS
  ^odoo/addons/alc_db_cleaner/|
  ^odoo/addons/alc_partner_delivery_person/|
  # END NOT INSTALLABLE ADDONS
  ^LICENCE$|
  ^scripts/odoo-16-migration/upgrade.py|
  ^scripts/svl-odoo
default_language_version:
  python: python3
  node: "22.9.0"
repos:
  - repo: https://github.com/acsone/maintainer-tools
    rev: 12183a1c51435fa0853583b8119a7ca8a4347f45
    hooks:
      # update the NOT INSTALLABLE ADDONS section above
      - id: oca-update-pre-commit-excluded-addons
        args: [--addons-dir=odoo/addons]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/myint/autoflake
    rev: v1.6.1
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: local
    hooks:
      - id: prettier
        name: prettier (with plugin-xml)
        entry: prettier
        args:
          - --write
          - --list-different
          - --ignore-unknown
        types: [text]
        files: \.(css|htm|html|js|json|jsx|less|md|scss|toml|ts|xml|yaml|yml)$
        language: node
        additional_dependencies:
          - "prettier@3.3.3"
          - "@prettier/plugin-xml@3.4.1"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: \.bumpversion\.cfg|/README\.rst$|\.pot?$
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.289"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/OCA/pylint-odoo
    rev: v9.1.3
    hooks:
      - id: pylint_odoo
        files: odoo/addons/
        args: ["--rcfile=.pylintrc"]
  - repo: https://github.com/OCA/odoo-pre-commit-hooks/
    rev: v0.0.23
    hooks:
      - id: oca-checks-odoo-module
      - id: oca-checks-po
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
  - repo: https://github.com/acsone/odoo-sort-manifest-depends
    rev: v1.4 # see the release page https://github.com/acsone/odoo-sort-manifest-depends/releases
    hooks:
      - id: odoo-sort-manifest-depends
        args:
          [
            --local-addons-dir=./odoo/addons/,
            --odoo-version=16.0,
            --project-name=Alcyon,
          ]
