exclude: |
  (?x)
  .pot$|
  ^odoo/addons/alc_b2c_connector\/utils.py|
  # NOT INSTALLABLE ADDONS
  ^odoo/addons/account_payment_order_background/|
  ^odoo/addons/alc_country/|
  ^odoo/addons/alc_db_cleaner/|
  ^odoo/addons/alc_delivery_rounds_geooptimize/|
  ^odoo/addons/alc_eshop_auth_api_key/|
  ^odoo/addons/alc_mrp_repair/|
  ^odoo/addons/alc_partner_delivery_person/|
  ^odoo/addons/alc_partner_delivery_window_import/|
  ^odoo/addons/alc_print_all_deliveryslip/|
  ^odoo/addons/alc_purchase_order_import_ubl/|
  ^odoo/addons/alc_shopfloor_mobile_workstation/|
  ^odoo/addons/alc_standby_delivery/|
  ^odoo/addons/alc_stock_picking_number_package/|
  ^odoo/addons/alc_stock_picking_wave_type/|
  ^odoo/addons/alc_stock_storage_type/|
  ^odoo/addons/alce_purchase_report/|
  ^odoo/addons/base_cached_xmlid/|
  ^odoo/addons/l10n_be_vat/|
  ^odoo/addons/partner_archive_new_partner/|
  ^odoo/addons/stock_inventory_constrains/|
  ^odoo/addons/test_alc_shopfloor_stock_issue_product_additional/|
  ^odoo/addons/test_product_additional_groupbypartner/|
  # END NOT INSTALLABLE ADDONS
  ^LICENCE$|
  ^scripts/odoo-16-migration/upgrade.py|
  ^scripts/svl-odoo
default_language_version:
  python: python3
  node: "16.17.0"
repos:
  - repo: https://github.com/acsone/maintainer-tools
    rev: 12183a1c51435fa0853583b8119a7ca8a4347f45
    hooks:
      # update the NOT INSTALLABLE ADDONS section above
      - id: oca-update-pre-commit-excluded-addons
        args: [--addons-dir=odoo/addons]
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        name: prettier (with plugin-xml)
        additional_dependencies:
          - "prettier@2.7.1"
          - "@prettier/plugin-xml@2.2.0"
        args:
          - --plugin=@prettier/plugin-xml
        files: \.(css|htm|html|js|json|jsx|less|md|scss|toml|ts|xml|yaml|yml)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: \.bumpversion\.cfg|/README\.rst$|\.pot?$
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.249
    hooks:
      - id: ruff
  - repo: https://github.com/OCA/pylint-odoo
    rev: v8.0.19
    hooks:
      - id: pylint_odoo
        files: odoo/addons/
        args: ["--rcfile=.pylintrc"]
  - repo: https://github.com/OCA/odoo-pre-commit-hooks/
    rev: v0.0.23
    hooks:
      - id: oca-checks-odoo-module
      - id: oca-checks-po
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort except __init__.py
        exclude: /__init__\.py$

  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.2
    hooks:
      - id: pydocstringformatter
  - repo: local
    hooks:
      - id: update-mypy-omit-addons
        name: update mypy exclude addons
        entry: ./scripts/update_mypy_exclude_addons.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        args: ["--addons-dir=odoo/addons"]
  # disabled because it's difficult to make it work with the current
  # structure of the repo and odoo
  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v0.982
  #  hooks:
  #  -   id: mypy
  #      args: ["--namespace-packages", "--explicit-package-bases", "--ignore-missing-imports", "--follow-imports=skip"]
  #      exclude : ^odoo/addons/.*/migrations/.*$
  #      additional_dependencies: [types-python-dateutil]

  - repo: https://github.com/returntocorp/semgrep
    rev: "v1.31.0"
    hooks:
      - id: semgrep
        args: ["--config", ".semgrep.yaml", "--error", "--metrics=off"]
