rules:
  - id: is-old-style-inheritance
    patterns:
      - pattern: _inherit = ...
      - pattern-inside: |
          class $CLASS_NAME(models.Model):
             ...
    message:
      "This class inherits from models.Model, which should be replace by python
      inheritance."
    languages: [python]
    severity: ERROR
  # define a rule that check if a field x2many don't use python generic syntax
  # like Many2one[<class>](...) but use the old syntax Many2one(...)
  - id: is-old-style-x2-without-generic
    patterns:
      - pattern: |
          $FIELD_NAME = fields.$FIELD_TYPE(...)
      - metavariable-comparison:
          metavariable: $FIELD_TYPE
          comparison: str($FIELD_TYPE) in ["One2many", "Many2many", "Many2one"]
    message: "This x2many field should use the generic syntax.\n"
    languages: [python]
    severity: ERROR
