version: '2'

services:
  akeneo:
    image: s7b4/akeneo-lite
    ports:
      - "9000:80"
    env_file: .akeneo.env
    volumes:
      - "data-akeneo:/var/www/html"
  mysql:
    image: mysql:5.6
    env_file: .akeneo.env
    volumes:
      - "data-mysql:/var/lib/mysql"

volumes:
  data-mysql:
  data-akeneo:
