#!/usr/bin/env python2
import os
import subprocess
import textwrap
from ConfigParser import ConfigParser

config = ConfigParser()
config.read("acsoo.cfg")

VERSION = config.get("acsoo", "version")
HOST = os.environ.get("host")
USER = os.environ.get("user")

subprocess.check_call(
    [
        "rsync",
        "--verbose",
        "--recursive",
        "--times",
        "--delete",
        "--rsync-path",
        "sudo -u {USER} rsync".format(**locals()),
        "release/",
        "{HOST}:/home/{USER}/instance/release/".format(**locals()),
    ]
)
subprocess.check_call(
    [
        "ssh",
        HOST,
        textwrap.dedent(
            """\
        sudo -u {USER} -H -s <<'EOF'
        set -ex
        cd /home/{USER}/instance
        ./installvenv {VERSION}
        ./maintenance_start
        rm -f venv
        ln -s venv-{VERSION} venv
        for db in $(cat DATABASES) ; do
            venv/bin/click-odoo-update -c odoo.cfg -d $db --i18n-overwrite
        done
        ./maintenance_stop
        EOF
    """.format(
                **locals()
            )
        ),
    ]
)
