version: '2'

services:
  wso2esb:
    image: isim/wso2esb
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8243:8243"
      - "8280:8280"
    volumes:
      - "data-wso2esb-server:/opt/wso2esb-4.9.0/repository/deployment/server"
      - "data-wso2esb-dropins:/opt/wso2esb-4.9.0/repository/components/dropins"
      - "data-wso2esb-lib:/opt/wso2esb-4.9.0/repository/components/lib"
      - "data-wso2esb-security:/opt/wso2esb-4.9.0/repository/resources/security"

volumes:
  data-wso2esb-server:
  data-wso2esb-dropins:
  data-wso2esb-lib:
  data-wso2esb-security:
