# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc App Account",
    "description": """Gather all account related modules for Alcyon""",
    "version": "16.0.1.0.3",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "depends": [
        # Custom
        "alc_account_invoice_accrual",
        "alc_account_invoice_email",
        "alc_account_invoice_peppol_server_env",
        "alc_account_invoice_product_no_reference",
        "alc_account_invoice_supplier_ref_unique_mandatory",
        "alc_account_invoice_vendor_bill_autocomplete",
        "alc_account_move_maturity_date",
        "alc_account_payment_globalization",
        "alc_account_security",
        "alc_account_tax_precision",
        "alc_automatic_account_move_line_reconcile",
        "alc_chronovet_payment_globalization",
        "alc_partner_invoicing_mode_default",
        "alc_placedesvetos_payment_globalization",
        # OCA
        "account_cutoff_accrual_order_product_category",
        "account_cutoff_accrual_purchase_stock",
        "account_cutoff_accrual_sale_stock",
        "account_financial_report",
        "account_invoice_accrual",
        "account_invoice_check_total",
        "account_invoice_line_default_account",
        "account_invoice_supplier_ref_unique",
        "account_invoice_transmit",
        "account_invoice_transmit_peppol",
        "account_journal_lock_date",
        "account_move_line_product_category",
        "account_move_sent_usability",
        "account_payment_mode_auto_reconcile",
        "account_reconcile_restrict_partner_mismatch",
        "account_reversal",
        "l10n_be_antibiotic_tax",
        "l10n_be_apb_tax",
        "l10n_be_eco_tax",
        "l10n_be_iso20022_pain",
        "mis_builder",
        "mis_builder_budget",
        "partner_invoicing_mode",
        "partner_invoicing_mode_at_shipping",
        "partner_invoicing_mode_at_shipping_fourteen_days",
        "partner_invoicing_mode_cash_on_delivery",
        "partner_invoicing_mode_fourteen_days",
        "partner_invoicing_mode_monthly",
        "partner_invoicing_mode_ten_days",
        "report_async",
        # Others
        "account",
    ],
    "data": [
        "data/report_async.xml",
    ],
}
