# generated by fastapi-codegen:
#   filename:  veterinary_groups.json
#   timestamp: 2023-10-30T15:37:21+00:00

from __future__ import annotations

from pydantic import BaseModel


class VeterinaryGroup(BaseModel):
    color: str | None = None
    sequence: int
    is_alcyonnaire: bool
    id: int
    name: str


class VeterinaryGroupList(BaseModel):
    data: list[VeterinaryGroup]
    size: int
