[outgoing_mail]
smtp_host = mailhog
smtp_port = 1025
smtp_encryption = none

[ir.config_parameter]
storage.image.backend_id=alc_storage.s3_images_backend
storage.thumbnail.backend_id=alc_storage.s3_images_backend
ribbon.name=PREPROD 2.6.117
ir_attachment.location=db

[edi_backend_zoetis]
channel = sftp
hostname = sftp.hbsolutions.de
username = alcyonbelux
password = mGCEWxGereMPksTVxjQY
port = 22
path_read = From_PageroHBS_Test
path_write = To_PageroHBS_Test
pk_env_variable =

[storage_backend.ImagesS3]
base_url=https://minio.acsone-k8s-test.acsone.eu/alcyon-test
aws_host=https://minio.acsone-k8s-test.acsone.eu
directory_path=images
aws_bucket=alcyon-test
aws_access_key_id=alcyon-test

[fs_storage.fstst_eshop]
base_url=https://media.pp.alcyon.acsone.eu
