# Copyright 2022 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc Order Picking App",
    "description": """
        Gather all order picking related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        "alc_additional_product_stock",
        "alc_delivery_carrier_gls",
        "alc_delivery_carrier_label_gls_server_env",
        "alc_partner_carrier",
        "alc_stock_available_immediately",
        "alc_stock_delivery_slip",
        "alc_stock_picking_backorder_reason",
        "alc_stock_picking_batch_assignment",
        "alc_stock_picking_wave_display",
        "base_delivery_carrier_label",
        "delivery_carrier_max_weight_constraint",
        "delivery_estimated_package_quantity_by_weight",
        "delivery_package_type_number_parcels",
        "internal_stock_quant_package",
        "product_total_weight_from_packaging",
        "shipment_advice",
        "stock_dynamic_routing",
        "stock_move_common_dest",
        "stock_move_location",
        "stock_move_manage_priority",
        "stock_move_propagate_first_move",
        "stock_picking_batch_creation",
        "stock_picking_backorder_reason",
        "stock_picking_backorder_reason_grn",
        "stock_picking_completion_info",
        "stock_picking_delivery_link",
        "stock_picking_group_by_partner_by_carrier",
        "stock_picking_group_by_partner_by_carrier_by_customer",
        "stock_picking_group_by_max_weight",
        "stock_picking_low_priority",
        "stock_picking_start",
        "stock_picking_type_shipping_policy",
        "stock_production_lot_expired_date",
        "stock_release_channel",
        "stock_release_channel_geoengine",
        "stock_release_channel_auto_release",
        "stock_release_channel_process_end_time",
        "stock_restrict_lot",
        "shipment_advice_planner",
        "shipment_advice_planner_toursolver",
        "shipment_advice_planner_toursolver_queue_job",
        "stock_release_channel_shipment_advice",
        "stock_release_channel_shipment_advice_toursolver",
        "stock_release_channel_shipment_advice_process_end_time",
        "alc_stock_location_data",
        "alc_mail_thread_no_auto_subscribe_notify",
        "alc_stock_picking_batch_creation",
        "alc_product_incoming_stock_move_action",
        "alc_product_is_new",
        "alc_stock_release_channel_tag",
        "alc_stock_release_channel_import",
        "alc_stock_release_channel_user",
        "alc_restocking_exclude_not_salable",
        "alc_stock_release_channel_pick_allowed",
    ],
    "data": [],
    "demo": [],
    "application": True,
    "installable": True,
}
