# Copyright 2022 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc Order Picking App",
    "description": """
        Gather all order picking related modules for Alcyon""",
    "version": "16.0.1.0.5",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        # Custom
        "alc_additional_product_stock",
        "alc_delivery_carrier_gls",
        "alc_delivery_carrier_gls_b2c",
        "alc_delivery_carrier_gls_report",
        "alc_delivery_carrier_label_gls_server_env",
        "alc_empty_package_at_picking_return",
        "alc_label_printing_base",
        "alc_label_printing_gls",
        "alc_label_printing_reception",
        "alc_mail_thread_no_auto_subscribe_notify",
        "alc_partner_carrier",
        "alc_product_abc_classification_storage_type",
        "alc_product_category_warning_info",
        "alc_product_expiry",
        "alc_product_incoming_stock_move_action",
        "alc_product_is_new",
        "alc_product_label_printer",
        "alc_product_label_printing",
        "alc_report_stock_location",
        "alc_restocking_exclude_not_salable",
        "alc_stock_available",
        "alc_stock_available_immediately",
        "alc_stock_delivery_slip",
        "alc_stock_location_data",
        "alc_stock_location_orderpoint_cleanup",
        "alc_stock_location_orderpoint_priority",
        "alc_stock_lot_is_empty",
        "alc_stock_move_direction",
        "alc_stock_move_line_audit",
        "alc_stock_move_line_lock_done",
        "alc_stock_move_line_package_level_index",
        "alc_stock_move_line_restrict_quantity",
        "alc_stock_move_location_by_supplier",
        "alc_stock_move_need_release",
        "alc_stock_picking_action_put_in_pack",
        "alc_stock_picking_backorder_no_user",
        "alc_stock_picking_backorder_reason",
        "alc_stock_picking_batch_assignment",
        "alc_stock_picking_batch_cancel",
        "alc_stock_picking_batch_creation",
        "alc_stock_picking_cancel_permission",
        "alc_stock_picking_manage_priority",
        "alc_stock_picking_name",
        "alc_stock_picking_put_in_pack_type_none",
        "alc_stock_picking_responsible_portal",
        "alc_stock_picking_type_aliment",
        "alc_stock_picking_validate_and_print",
        "alc_stock_picking_view",
        "alc_stock_picking_wave_display",
        "alc_stock_quant_product_last_transaction",
        "alc_stock_quant_product_supplier",
        "alc_stock_receive_lot_expiry",
        "alc_stock_refill_view",
        "alc_stock_release_channel_assign_blocking_unavailable_product",
        "alc_stock_release_channel_code",
        "alc_stock_release_channel_dashboard",
        "alc_stock_release_channel_deliver_gls",
        "alc_stock_release_channel_deliver_toursolver",
        "alc_stock_release_channel_import",
        "alc_stock_release_channel_partner_holidays",
        "alc_stock_release_channel_pick_allowed",
        "alc_stock_release_channel_picking_batch_creation",
        "alc_stock_release_channel_plan",
        "alc_stock_release_channel_print_cash_on_delivery",
        "alc_stock_release_channel_print_shipment_advice",
        "alc_stock_release_channel_sequence",
        "alc_stock_release_channel_state_editable",
        "alc_stock_release_channel_tag",
        "alc_stock_release_channel_tree",
        "alc_stock_release_channel_user",
        "alc_stock_release_channel_user_gls",
        "alc_stock_security",
        "alc_stock_warehouse_configuration",
        # OCA
        "base_delivery_carrier_label",
        "base_report_to_label_printer",
        "delivery_carrier_max_weight_constraint",
        "delivery_estimated_package_quantity_by_weight",
        "delivery_package_type_number_parcels",
        "internal_stock_quant_package",
        "product_expiry_configurable",
        "product_total_weight_from_packaging",
        "shipment_advice",
        "shipment_advice_planner",
        "shipment_advice_planner_toursolver",
        "shipment_advice_planner_toursolver_queue_job",
        "stock_available_base_exclude_location",
        "stock_available_location_orderpoint",
        "stock_available_to_promise_release_exclude_location",
        "stock_dynamic_routing",
        "stock_full_location_reservation",
        "stock_location_orderpoint",
        "stock_location_orderpoint_average_daily_sale",
        "stock_location_orderpoint_change_priority",
        "stock_location_orderpoint_cleanup",
        "stock_location_orderpoint_dynamic_routing_merge",
        "stock_lot_is_archived",
        "stock_move_common_dest",
        "stock_move_line_change_lot",
        "stock_move_line_lock_qty_done",
        "stock_move_location",
        "stock_move_manage_priority",
        "stock_move_priority_picking_assign",
        "stock_move_propagate_first_move",
        "stock_move_propagate_first_move_cancel",
        "stock_picking_backorder_reason",
        "stock_picking_backorder_reason_grn",
        "stock_picking_batch_creation",
        "stock_picking_batch_start",
        "stock_picking_completion_info",
        "stock_picking_delivery_link",
        "stock_picking_group_by_max_weight",
        "stock_picking_group_by_partner_by_carrier",
        "stock_picking_group_by_partner_by_carrier_by_customer",
        "stock_picking_low_priority",
        "stock_picking_operation_loss_quantity",
        "stock_picking_progress",
        "stock_picking_start",
        "stock_picking_type_shipping_policy",
        "stock_production_lot_expired_date",
        "stock_quant_safe_inventory",
        "stock_release_channel",
        "stock_release_channel_auto_release",
        "stock_release_channel_geoengine",
        "stock_release_channel_plan_process_end_time",
        "stock_release_channel_process_end_time",
        "stock_release_channel_propagate_channel_picking",
        "stock_release_channel_shipment_advice",
        "stock_release_channel_shipment_advice_deliver",
        "stock_release_channel_shipment_advice_process_end_time",
        "stock_release_channel_shipment_advice_toursolver",
        "stock_reserve_rule",
        "stock_restrict_lot",
        "stock_split_picking",
    ],
    "data": [],
    "demo": [],
    "application": True,
    "installable": True,
}
