{
    'name': 'Stock Delivery Note',
    'summary': 'Creates a specific delivery note in csv format',
    'version': '10.0.1.0.0',
    'author': 'Camptocamp',
    'maintainer': 'Camptocamp',
    'license': 'AGPL-3',
    'category': 'Stock',
    'depends': [
        'specific_data',
        'specific_sale',
        'stock',
        'specific_stock',
        'product_expiry',
        'stock_expired',
    ],
    'data': [
        'data/email_template.xml',
        'views/stock_picking.xml',
        'views/stock_move.xml',
    ],
    'website': 'www.camptocamp.com',
    'installable': True,
    'auto_install': False,
    'application': False,
}
