# -*- coding: utf-8 -*-
# Copyright 2016 Julien Coux (Camptocamp)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Specific stock for Alcyon",
    "version": "10.0.1.0.3",
    "author": "Camptocamp",
    "license": "AGPL-3",
    "category": "Warehouse",
    "depends": [
        "alc_internal_stock_quant_package",
        "alc_stock_receive_lot_expiry",
        "alc_stock_receive_lot_inputmask",
        "alc_product_lot_info",
        "alc_product_mto",
        "alc_stock_quant_package_nbr",
        "board",
        "delivery_rounds",
        "product",
        "product_expiry",
        "product_last_transaction",
        "purchase",
        "sale",
        "sale_stock",
        "specific_data",
        "specific_purchase",
        "stock",
        "stock_available_immediately",
        "stock_expired",
        "stock_groupbypartner",
        "stock_inventory_products",
        "stock_location",
        "stock_mts_mto_rule",
        "stock_operation_recompute",
        "stock_picking_assignment",
        "stock_picking_backorder",
        "stock_picking_zone",
        "stock_product_bin",
        "stock_receive_lot",
        "stock_reception_priority",
        "stock_refill",  # field 'kind' on stock.location
        "mrp",
    ],
    "website": "http://www.camptocamp.com",
    "data": [
        # Data
        "data/ir_cron.xml",
        "data/ir_config_parameter.xml",
        "data/product.category.csv",
        "data/ir_sequence.xml",
        # Views
        "views/product_category.xml",
        "views/product_template.xml",
        "views/res_partner.xml",
        "views/stock_location.xml",
        "views/stock_production_lot.xml",
        "views/stock_config_settings.xml",
        "views/stock_quant.xml",
        "views/stock_move.xml",
        "views/stock_inventory.xml",
        # Wizards
        "wizards/location_checksum.xml",
        "wizards/stock_receive_lot.xml",
        "wizards/stock_picking_return_views.xml",
        "wizards/stock_move_update_handler.xml",
        "wizards/put_in_pack_helper.xml",
        "wizards/generate_voice_identifier.xml",
        "wizards/open_uop.xml",
        # Views (loaded after wizards)
        "views/stock_picking.xml",
        # Security
        "security/ir.model.access.csv",
        "security/ir_ui_menu.xml",
    ],
    "installable": False,
}
