# -*- coding: utf-8 -*-
# Copyright 2018 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl)
{'name': 'Tests for DB2 Import',
 'version': '10.0.1.0.0',
 'author': 'Camptocamp',
 'maintainer': 'Camptocamp',
 'license': 'AGPL-3',
 'category': 'Testing',
 'depends': [
     # Install all related addons to apply import test on them
     # Odoo
     'l10n_be',
     'l10n_be_intrastat',
     'product',
     'purchase',
     'sale',
     # OCA
     # oca/account-financial-tools/
     'account_chart_update',
     # oca/account-invoicing
     'account_invoice_check_total',
     'account_invoice_line_default_account',
     'account_invoice_triple_discount',
     # oca/bank-payment
     'account_banking_sepa_credit_transfer',
     'account_banking_sepa_direct_debit',
     # 'account_invoice_tax_required',
     'account_payment_mode',
     'account_payment_order',
     'account_payment_partner',
     # oca/l10n-belgium
     'l10n_be_antibiotic_tax',
     'l10n_be_apb_tax',
     'l10n_be_eco_tax',
     # oca/product-attribute
     'product_manufacturer',
     # oca/sale-workflow
     'sale_exception',
     'sale_triple_discount',
     # oca/stock-logistics-warehouse
     'stock_available_immediately',
     # OCA/stock-logistics-workflow
     'stock_picking_invoice_link',
     # local-src
     'account_move_productcateg',
     'connector_esb',
     'db2_import',
     'delivery_rounds',
     'pricelist_discount',
     'procurement_sale',
     'product_additional',
     'refund_invoice',
     'sale_cancel_remaining',
     'specific_account',
     'specific_base',
     'specific_data',
     'specific_followup',
     'specific_helpdesk',
     'specific_partner',
     'specific_print',
     'specific_product',
     'specific_purchase',
     'specific_purchase_report',
     'specific_report',
     'specific_sale',
     'specific_shipping_costs',
     'specific_stock',
     'specific_zetes',
     'stock_barcode_fix',
     'stock_expired',
     'stock_grn',
     'stock_groupbypartner',
     'stock_lot_track',
     'stock_location',
     'stock_lot_update',
     'stock_picking_assignment',
     'stock_picking_fillwithstock',
     'stock_picking_sequence',
     'stock_product_bin',
     'stock_production_lot_expired_dates',
     'stock_putaway_defaultfixedlocation',
     'stock_putaway_route',
     'stock_quant_bylocation',
     'stock_receive_lot',
     'stock_reception_priority',
     'stock_refill',
     'stock_valuation',
     ],
 'website': 'www.camptocamp.com',
 'data': [],
 'test': [],
 'installable': True,
 'auto_install': False,
 }
