# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc App Eshop B2b",
    "description": """
        Gather all B2B related modules for Alcyon""",
    "version": "16.0.1.0.2",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "application": True,
    "depends": [
        # Custom
        "alc_base_multi_media_lang",
        "alc_connector_esb",
        "alc_elasticsearch_price_sorting",
        "alc_elasticsearch_role",
        "alc_elasticsearch_score_script",
        "alc_elasticsearch_security",
        "alc_elasticsearch_security_vt_groups",
        "alc_eshop_ads",
        "alc_eshop_api",
        "alc_eshop_classifieds",
        "alc_eshop_classifieds_responsible",
        "alc_eshop_info_banner",
        "alc_eshop_models_url",
        "alc_eshop_ordering_allowed",
        "alc_eshop_product",
        "alc_eshop_product_additional_price",
        "alc_eshop_product_audit",
        "alc_eshop_product_brand",
        "alc_eshop_product_dimensions",
        "alc_eshop_product_discount_special",
        "alc_eshop_product_domain",
        "alc_eshop_product_food",
        "alc_eshop_product_link_notice",
        "alc_eshop_product_packaging",
        "alc_eshop_product_partner_type",
        "alc_eshop_product_pharmacy",
        "alc_eshop_product_pim",
        "alc_eshop_product_price_cache",
        "alc_eshop_product_promoted_links",
        "alc_eshop_product_route_mto",
        "alc_eshop_product_storage_temperature",
        "alc_eshop_product_supplier",
        "alc_eshop_product_supplier_promotion",
        "alc_eshop_product_tax",
        "alc_eshop_product_veterinary_group",
        "alc_eshop_schema_address",
        "alc_eshop_search_engine_ads",
        "alc_eshop_search_engine_assortment_bind",
        "alc_eshop_search_engine_category",
        "alc_eshop_search_engine_image",
        "alc_eshop_search_engine_info_banner",
        "alc_eshop_search_engine_manual_export",
        "alc_eshop_search_engine_product_expiry",
        "alc_eshop_search_engine_product_media",
        "alc_eshop_search_engine_product_stock",
        "alc_eshop_search_engine_product_stock",
        "alc_eshop_search_engine_product_url_locales",
        "alc_eshop_search_engine_update_product_discount_special",
        "alc_eshop_search_engine_update_veterinary_group",
        "alc_keycloak",
        "alc_price_cache",
        "alc_price_cache_exclusive",
        "alc_price_cache_import",
        "alc_product_assortment",
        "alc_product_promotion_mailing",
        "alc_sale_cart_price_recalculation",
        "connector_keycloak",
        "elasticsearch_security",
        "elasticsearch_security_mixin",
        # OCA
        "fs_product_brand_multi_image",
        "fs_product_multi_image",
        "fs_product_multi_media",
        "shopinvader_base_url",
        "shopinvader_es_product_categ",
        "shopinvader_multi_category",
        "shopinvader_product_attribute_set",
        "shopinvader_product_brand",
        "shopinvader_product_description",
        "shopinvader_product_seo",
        "shopinvader_product_url",
        "shopinvader_search_engine",
        "shopinvader_search_engine_assortment",
        "shopinvader_search_engine_image",
        "shopinvader_search_engine_product_brand",
        "shopinvader_search_engine_product_brand_image",
        "shopinvader_search_engine_product_media",
        "shopinvader_search_engine_product_stock",
        "shopinvader_search_engine_product_stock_state",
        "shopinvader_search_engine_product_template_multi_link",
        "shopinvader_search_engine_update",
        "shopinvader_search_engine_update_image",
        "shopinvader_search_engine_update_product_brand",
        "shopinvader_search_engine_update_product_brand_image",
        "shopinvader_search_engine_update_product_media",
        "shopinvader_search_engine_update_product_template_multi_link",
    ],
    "data": [
        "security/res_groups.xml",
        "views/eshop_app_menu.xml",
        "data/se_thumbnail_size.xml",
        "data/se_index_config.xml",
        "data/se_index.xml",
        "data/se_image_field_thumbnail_size.xml",
    ],
    "demo": [],
    "development_status": "Alpha",
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
}
