# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc App Eshop B2b",
    "description": """
        Gather all B2B related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "application": True,
    "depends": [
        # OCA/storage
        "fs_product_brand_multi_image",
        "fs_product_multi_image",
        "fs_product_multi_media",
        # ALC
        "alc_price_cache",
        "alc_price_cache_exclusive",
        "alc_product_assortment",
        "alc_base_multi_media_lang",
        "alc_eshop_classifieds",
        "alc_eshop_ads",
        "alc_eshop_classifieds_responsible",
        "alc_eshop_ordering_allowed",
        "alc_eshop_info_banner",
        "alc_eshop_search_engine_info_banner",
        "alc_eshop_api",
        "alc_eshop_search_engine_ads",
        "connector_keycloak",
        "elasticsearch_security",
        "elasticsearch_security_mixin",
        "alc_elasticsearch_security",
        "alc_elasticsearch_role",
        "alc_elasticsearch_security_vt_groups",
        "alc_keycloak",
        "alc_eshop_schema_address",
        "alc_eshop_search_engine_product_expiry",
        "alc_sale_cart_price_recalculation",
        "alc_connector_esb",
        "alc_eshop_product",
        "alc_eshop_product_additional_price",
        "alc_eshop_product_audit",
        "alc_eshop_product_brand",
        "alc_eshop_product_dimensions",
        "alc_eshop_product_discount_special",
        "alc_eshop_product_food",
        "alc_eshop_product_link_notice",
        "alc_eshop_product_packaging",
        "alc_eshop_product_partner_type",
        "alc_eshop_product_pharmacy",
        "alc_eshop_product_pim",
        "alc_eshop_product_price_cache",
        "alc_eshop_product_storage_temperature",
        "alc_eshop_product_supplier",
        "alc_eshop_product_supplier_promotion",
        "alc_eshop_product_tax",
        # shopinvader
        "shopinvader_search_engine",
        "shopinvader_search_engine_image",
        "shopinvader_product_seo",
        "shopinvader_product_description",
        "shopinvader_product_brand",
        "shopinvader_base_url",
        "shopinvader_search_engine_product_brand",
        "shopinvader_search_engine_product_brand_image",
        "shopinvader_search_engine_product_media",
        "shopinvader_search_engine_product_template_multi_link",
        "shopinvader_product_url",
        "shopinvader_search_engine_update",
        "shopinvader_search_engine_update_image",
        "shopinvader_search_engine_update_product_media",
        "shopinvader_search_engine_update_product_brand",
        "shopinvader_search_engine_update_product_brand_image",
        "shopinvader_search_engine_update_product_template_multi_link",
        "shopinvader_search_engine_product_stock",
        "shopinvader_search_engine_product_stock_state",
        "shopinvader_product_attribute_set",
    ],
    "data": [],
    "demo": [],
    "development_status": "Alpha",
}
