# -*- coding: utf-8 -*-
{
    "name": "Stock Delivery Note",
    "summary": "Creates a specific delivery note in csv format",
    "version": "10.0.1.0.0",
    "author": "Camptocamp",
    "maintainer": "Camptocamp",
    "license": "AGPL-3",
    "category": "Stock",
    "depends": [
        "alc_b2c_partner",
        "alc_partner_veterinary",
        "alc_sale_suite_name",
        "product_additional",
        "product_expiry",
        "specific_data",
        "specific_sale",
        "specific_stock",
        "stock",
        # TODO: has been removed "stock_expired",
        "account_tax_one_vat",
        "alc_product_category_data",
    ],
    "data": [
        "views/res_partner.xml",
        "data/email_template.xml",
        "views/stock_picking.xml",
        "views/stock_move.xml",
    ],
    "website": "https://www.camptocamp.com",
    "installable": False,
    "auto_install": False,
    "application": False,
    "external_dependencies": {"python": ["unicodecsv", "unidecode"]},
}
