# -*- coding: utf-8 -*-
# Copyright 2018 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)
from pkg_resources import resource_stream

import anthem
from anthem.lyrics.modules import update_translations
from anthem.lyrics.records import add_xmlid
from anthem.lyrics.loaders import load_csv_stream

from ..common import req


@anthem.log
def fix_signature_date_on_mandate(ctx):
    """ The previous import of mandates contained two errors
    with signature date.
    These two date had been settled with the last debit date
    (wrong date in the data file generated by accountant).
    To avoid an error with a constrains on mandate, we set the date before."""
    mandate_360118579068 = ctx.env.ref(
        '__import__.mandate_4022_360118579068',
        raise_if_not_found=False
    )
    if mandate_360118579068:
        mandate_360118579068.write({
            'signature_date': '2005-04-19'
        })

    mandate_335022344196 = ctx.env.ref(
        '__import__.mandate_6521_335022344196',
        raise_if_not_found=False
    )
    if mandate_335022344196:
        mandate_335022344196.write({
            'signature_date': '2009-09-18'
        })


@anthem.log
def update_module_translations(ctx):
    """ Update translations for : specific_sale """
    update_translations(ctx, ['specific_sale'])


@anthem.log
def add_apb_tax_2018(ctx):
    ref = ctx.env.ref
    xmlid_old = 'l10n_be_apb_tax.1_apb_01_out'
    xmlid_2018 = 'l10n_be_apb_tax.1_apb_02_out'
    apb_tax_2018 = ref(xmlid_2018, raise_if_not_found=False)
    if not apb_tax_2018:
        apb_tax_old = ref(xmlid_old)
        apb_tax_2018 = apb_tax_old.copy()

        # rename old tax
        apb_tax_old.write({
            'name': 'APB Out (old)',
            'description': 'APB-OUT used before 2018-04-23',
        })

        # setup new tax value
        apb_tax_2018.amount = 0.02292

        # tax created by template needs to be noupdate
        add_xmlid(ctx, apb_tax_2018, xmlid_2018, noupdate=True)


@anthem.log
def import_customers(ctx):
    load_ctx = ctx.env.context.copy()
    load_ctx.update({'tracking_disable': True})
    Partner = ctx.env['res.partner'].with_context(load_ctx)

    file_list = [
        'customer.new.csv',
        'customer.change-property_product_pricelist.csv',
        'customer.change-comment.csv',
        'customer.change-active-call_name-is_sale_back_order_accepted.csv',
        'customer.change-active.csv',
        'customer.change-email.csv',
        'customer.change-comment-city-name-street-suite-email-call_name.csv',
        'customer.change-help_with_fee.csv',
        'customer.change-call_name.csv',
        'customer.change-street.csv',
        'customer.change-help_with_fee-discount_pricelist_id.csv',
        'customer.change-vet_depot_number.csv',
        'customer.change-street-email.csv',
        'customer.change-is_sale_back_order_accepted.csv',
        'customer.change-help_with_fee-invoice_sending_method-street-email-pharmacist_id.csv',  # noqa
        'customer.change-phone-street-email.csv',
        'customer.change-active-call_name.csv',
        'customer.change-comment-pharmacist_id.csv',
        'customer.change-discount_pricelist_id.csv',
        'customer.change-call_name-customer_payment_mode_id-name.csv',
        'customer.change-invoice_sending_method-street-email.csv',
        'customer.change-call_name-discount_pricelist_id-name-property_product_pricelist-user_id.csv',  # noqa
        'customer.change-comment-mobile.csv',
        'customer.change-email-alcyon_category_id-property_product_pricelist.csv',  # noqa
        'customer.change-suite-call_name-customer_payment_mode_id-name.csv',
        'customer.change-user_id.csv',
        'customer.change-suite-call_name-vet_depot_number-vet_subscription_number.csv',  # noqa
        'customer.change-city-street-property_product_pricelist-zip.csv',
        'customer.change-active-is_sale_back_order_accepted-call_name-customer_payment_mode_id-name.csv',  # noqa
        'customer.change-invoice_sending_method.csv',
        'customer.change-mobile.csv',
        'customer.change-discount_pricelist_id-vet_depot_number-property_product_pricelist.csv',  # noqa
        'customer.change-vet_depot_number-alcyon_category_id.csv',
        'customer.change-city-street-vet_depot_number-zip.csv',
        'customer.change-help_with_fee-supplier_promotion_sale_allowed-discount_pricelist_id.csv',  # noqa
        'customer.change-pharmacist_id-email-property_product_pricelist.csv',
        'customer.change-email-is_price_on_labels.csv',
        'customer.change-invoice_sending_method-email.csv'
    ]

    for f in file_list:
        base_path = 'data/update/10.24.0/'
        f_path = base_path + f
        with ctx.log(u"Importing customer file: %s" % f_path):
            content = resource_stream(req, f_path)
            load_csv_stream(ctx, Partner, content, delimiter=',')


@anthem.log
def pre(ctx):
    """ PRE 10.24.0 """
    update_module_translations(ctx)


@anthem.log
def post(ctx):
    """ POST 10.24.0 """
    add_apb_tax_2018(ctx)


@anthem.log
def pre_full(ctx):
    """ PRE FULL 10.24.0 """
    fix_signature_date_on_mandate(ctx)
