[ir.config_parameter]
ribbon.name=Dev

[api_key_chronovet_rest_api]
user=alc_chronovet_rest_api_user
backend_name=Chronovet
key=

[delivery_carrier.GLS Belgique]
gls_url=https://shipit-wbm-test01.gls-group.eu:8443/backend/rs/
gls_url_test=https://shipit-wbm-test01.gls-group.eu:8443/backend/rs/
gls_url_tracking=https://gls-group.eu/EU/en/parcel-tracking/match=%%s
prod_environment=False
gls_contact_id=056aaac2ea

[se_backend.elasticsearch_backend]
index_prefix_name=alc

[peppol_server.edido]
url="https://test.api.edido.eu/peppol/send_ubl"
url_feedback="https://test.api.edido.eu/peppol/get_sending_status"
user="TEST"
password="PWD"
