# -*- coding: utf-8 -*-
# Copyright 2017 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Specific ESB for Alcyon',
    'version': '10.0.1.0.0',
    'author': 'Camptocamp',
    'license': 'AGPL-3',
    'category': 'Connector',
    'depends': [
        'connector',
        'delivery_rounds',
        'onchange_helper',
        'pricelist_discount',
        'procurement_sale',
        'product',
        'product',
        'product_expiry',
        'product_manufacturer',
        'product_price_category',
        'purchase',
        'sale',
        'sale_delay',
        'sale_stock',
        'specific_base',
        'specific_partner',
        'specific_print',
        'specific_product',
        'specific_purchase',
        'specific_stock',
        'specific_data',
        'specific_sale',
        'stock',
        'product_additional',
        'queue_job_cron',
        'sale_confirm_background',
        'l10n_be_apb_tax',
        'delivery',
    ],
    'website': 'http://www.camptocamp.com',
    'data': [
        'data/esb_backend.xml',
        'data/esb_backend_timestamp.xml',
        'data/product.category.csv',
        'data/product_state.xml',
        'data/res_lang.xml',
        'data/ir_cron.xml',
        'views/esb_backend_views.xml',
        'views/account_tax_views.xml',
        'views/product_views.xml',
        'views/product_uom_views.xml',
        'views/product_state_views.xml',
        'views/product_pricelist.xml',
        'views/product_category_views.xml',
        'views/partner_alcyon_category.xml',
        'views/res_users.xml',
        'views/res_country.xml',
        'views/res_lang_views.xml',
        'views/delivery_carrier.xml',
        'views/sale_order.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'external_dependencies': {
        'python': ['paramiko', 'simplejson', 'dicttoxml'],
    },
}
