# -*- coding: utf-8 -*-
# Copyright 2021 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Alc Shopfloor App",
    "description": """
        Alcyon: Shopfloor App""",
    "version": "10.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        "alc_shopfloor",
        "alc_shopfloor_cluster_picking",
        "alc_shopfloor_cluster_picking_by_partners",
        "alc_shopfloor_cluster_picking_out_location",
        "alc_shopfloor_cluster_picking_printing",
        "alc_shopfloor_cluster_picking_stock_issue_all_products",
        "alc_shopfloor_cluster_picking_transfer_async",
        "alc_shopfloor_delivery_rounds",
        "alc_shopfloor_image_product",
        "alc_shopfloor_location_content_relocation",
        "alc_shopfloor_location_info",
        "alc_shopfloor_product_info",
        "alc_shopfloor_assignation_issue_message",
        "alc_shopfloor_mobile",
        "alc_shopfloor_mobile_change_pack_lot_back_button",
        "alc_shopfloor_mobile_cluster_picking",
        "alc_shopfloor_mobile_cluster_picking_informations",
        "alc_shopfloor_mobile_cluster_picking_workstation",
        "alc_shopfloor_mobile_image_product",
        "alc_shopfloor_mobile_packing",
        "alc_shopfloor_mobile_product_print_label",
        "alc_shopfloor_mobile_qty_picker_font_style",
        "alc_shopfloor_mobile_stock_issue_button",
        "alc_shopfloor_mobile_stock_refill",
        "alc_shopfloor_mobile_stock_reserve",
        "alc_shopfloor_version",
        "alc_shopfloor_mobile_workstation",
        "alc_shopfloor_rest_log",
        "alc_shopfloor_unassign_wave",
        "alc_shopfloor_user",
        "alc_shopfloor_workstation",
        "shopfloor_workstation_mobile",
    ],
    "demo": [],
    "application": True,
    'installable': False
}