# -*- coding: utf-8 -*-
# Copyright 2021 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).


{
    "name": "Alcyon E-Shop",
    "description": """Install all apps and modules required by Shopinvader""",
    "version": "10.0.2.0.1",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        "product_discount_specials",
        "alc_pim",
        "alc_storage",
        "alc_supplier_promotion",
        "alc_price_cache_import",
        "alc_eshop_api_v2",
        "alc_eshop_auth_api_key",
        "alc_eshop_auth_jwt",
        "alc_eshop_customer_sales_person",
        "alc_eshop_filter_data",
        "alc_eshop_sale_channel",
        "alc_eshop_sale_payment_info",
        "alc_eshop_sale_product_unavailable",
        "alc_eshop_sale_qty_canceled",
        "alc_eshop_sale_no_backend",
        "alc_eshop_sale_suite_name",
        "alc_shopinvader_category",
        "alc_shopinvader_fixes",
        "alc_eshop_wishlist",
        "alc_product_promoted_links",
        "alc_product_stock_state",
        "alc_partner_veterinary",
        "shopinvader_auth_jwt",
        "shopinvader_elasticsearch",
        "shopinvader_product_media",
        "shopinvader_product_template_multi_link",
        "shopinvader_product_stock_state",
        "shopinvader_multi_category",
        "shopinvader_assortment",
        "shopinvader_image",
        "shopinvader_wishlist",
        "shopinvader_search_engine_update",
        "shopinvader_search_engine_export",
        "shopinvader_url_locales",
    ],
    "application": False,
    "data": [
        "data/auth_jwt_validator.xml",
        "data/shopinvader_image_resize.xml",
        "data/product_pricelist.xml",
        "data/shopinvader_backend.xml",
        "views/shopinvader_backend.xml",
    ],
    "demo": [],
    'installable': False
}