# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc App Shopfloor",
    "description": """
        Gather all shopfloor related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "depends": [
        # Custom
        "alc_shopfloor_cluster_picking_by_partners",
        "alc_shopfloor_cluster_picking_cancel_on_unassign",
        "alc_shopfloor_cluster_picking_exclude_apply_dynamic_routing",
        "alc_shopfloor_cluster_picking_out_location",
        "alc_shopfloor_cluster_picking_printing",
        "alc_shopfloor_cluster_picking_stock_issue_all_products",
        "alc_shopfloor_cluster_picking_transfer_async",
        "alc_shopfloor_cluster_picking_workstation",
        "alc_shopfloor_image_product",
        "alc_shopfloor_location_content_transfer_sorter",
        "alc_shopfloor_loss_quantity",
        "alc_shopfloor_lot_scan",
        "alc_shopfloor_mobile_cluster_picking",
        "alc_shopfloor_mobile_cluster_picking",
        "alc_shopfloor_mobile_cluster_picking_informations",
        "alc_shopfloor_mobile_cluster_picking_workstation",
        "alc_shopfloor_mobile_image_product",
        "alc_shopfloor_mobile_product_print_label",
        "alc_shopfloor_mobile_qty_picker_font_style",
        "alc_shopfloor_mobile_stock_issue_button",
        "alc_shopfloor_mobile_stock_reserve",
        "alc_shopfloor_product_info",
        "alc_shopfloor_product_print_label",
        "alc_shopfloor_security",
        "alc_shopfloor_stock_picking_batch_assignment",
        "alc_shopfloor_stock_refill",
        "alc_shopfloor_stock_release_channel",
        "alc_shopfloor_stock_reserve",
        "alc_shopfloor_user",
        "alc_shopfloor_version",
        "alc_shopfloor_workstation",
        # OCA
        "shopfloor",
        "shopfloor_batch_automatic_creation",
        "shopfloor_full_location_reservation",
        "shopfloor_mobile",
        "shopfloor_mobile_base_auth_api_key",
        "shopfloor_mobile_packing",
        "shopfloor_packing",
        "shopfloor_rest_log",
        "shopfloor_workstation",
        "shopfloor_workstation_mobile",
    ],
    "data": [],
    "demo": [],
    "development_status": "Alpha",
}
