# Copyright 2020 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Alc All",
    "description": """
        Alcyon Odoo App""",
    "version": "16.0.2.14.2",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        # OCA
        "attachment_unindex_content",
        "base_technical_features",
        "server_environment",
        "server_environment_ir_config_parameter",
        "web_environment_ribbon",
        "web_chatter_position",
        "web_refresher",
        "web_search_with_and",
        "web_sheet_full_width",
        "web_tree_many2one_clickable",
        "web_remember_tree_column_width",
        "web_dialog_size",
        # ALC
        "alc_app_analytic",
        "alc_app_framework",
        "alc_app_invoicing",
        "alc_app_order_picking",
        "alc_app_purchase",
        "alc_app_putaway",
        "alc_app_receipt",
        "alc_app_return",
        "alc_app_rma",
        "alc_app_sale",
        "alc_app_eshop_b2b",
        "alc_app_account",
        "alc_app_account_payment",
        "alc_app_margin_analysis",
        "alc_app_shopfloor",
        "alc_edi_connector",
        "alc_fs_attachment",
        "alc_running_env",
        "alc_search_by_vendor_product_code",
        "alc_product_search_more_tree_view",
        # Configuration modules
        "alc_stock_available_immediately_loss",
        "stock_scrap_location_default",
        "alc_partner_holidays",
        "alc_partner_message_subscribe",
        "alc_partner_name",
        "alc_app_data",
        "alc_app_b2c",
        "alc_turnover_reporting",
        "alc_magento_api",
        "alc_report_qweb_pdf_batch",
        # TO BE REMOVED
        "base_report_to_printer",
    ],
    "application": True,
    "data": [
        "security/sale_order.xml",
        "security/product_state.xml",
        "security/res_groups.xml",
        "views/product_packaging.xml",
        "views/product_template.xml",
        "views/res_partner.xml",
        "data/decimal_precision.xml",
        "data/ir_config_parameter.xml",
        "data/ir_sequence.xml",
        "data/res_company.xml",
        "data/se_backend.xml",
        "data/stock_location.xml",
        "data/stock_picking_type.xml",
        "data/stock_route.xml",
        "data/stock_rule.xml",
        "data/stock_location_orderpoint.xml",
        "data/stock_warehouse.xml",
        "data/shopinvader_assortment.xml",
        "data/res_lang.xml",
    ],
    "demo": [],
    "development_status": "Alpha",
}
