# -*- coding: utf-8 -*-
# Copyright 2020 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Alc All",
    "description": """
        Alcyon Odoo App""",
    "version": "10.0.1.56.10",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu/",
    "depends": [
        "server_environment_files",
        # external
        "account_invoice_merge_attachment",
        "product_sequence",
        "account_analytic_no_lines",
        "account_financial_report_date_range",
        "mass_editing",
        "account_invoice_force_number",
        "account_invoice_line_default_account",
        "account_invoice_merge",
        "account_invoice_tax_required",
        "account_type_menu",
        "analytic_tag_dimension_purchase_warning",
        "account_analytic_required",
        "account_mass_reconcile_partner",
        "web_sheet_full_width",
        "web_widget_many2many_tags_multi_selection",
        "analytic_tag_dimension_sale_warning",
        "stock_disable_force_availability_button",
        "web_environment_ribbon",
        "web_cache_name_get",
        "web_decimal_numpad_dot",
        "web_widget_color",
        "base_import_security_group",
        "account_payment_sale",
        "mis_builder",
        "account_banking_mandate",
        "account_invoice_merge_purchase",
        "account_cutoff_accrual_return",
        "account_invoice_accrual_merge",
        "l10n_be_eco_tax",
        "account_mass_reconcile",
        "account_invoice_payment_report",
        "account_group",
        "mail_environment",
        "sql_request_abstract",
        "account_payment_mode_auto_reconcile",
        "account_banking_sepa_direct_debit",
        "product_analytic_purchase",
        "monitoring_status",
        "base_attachment_object_storage",
        "account_invoice_split_refund",
        "l10n_be_iso20022_pain",
        "account_banking_sepa_credit_transfer",
        "server_environment_ir_config_parameter",
        "account_reconcile_restrict_partner_mismatch",
        "auto_reconcile_structured_ref",
        "account_chart_update",
        "account_move_line_report_xls",
        "mis_builder_budget",
        "account_financial_report_qweb",
        "web_export_view",
        "server_environment",
        "analytic_tag_dimension",
        "base_import_async",
        "base_technical_features",
        "l10n_be_mis_reports",
        "base_optional_quick_create",
        "sale_stock_picking_blocking",
        "purchase_delivery_split_date",
        "base_geolocalize_openstreetmap",
        "geoengine_base_geolocalize",
        "base_geoengine",
        "sale_stock_restocking_fee_invoicing",
        "stock_location_product_restriction",
        # specific
        "alc_running_env",
        # "alc_geo_delivery_rounds",
        "account_move_productcateg",
        "account_payment_order_background",
        "account_tax_one_vat",
        "alc_account_payment_globalization",
        "alc_analytic_category_report",
        "alc_b2c_connector",
        "alc_b2c_to_magento",
        "alc_chronovet",
        "alc_chronovet_to_magento",
        "alc_chronovet_payment_globalization",
        "alc_delivery_rounds_partner_geolocalize",
        "alc_edi_connector",
        "alc_product_uom_updatable",
        "alc_sale_invoicing_on_transfer",
        "alc_sale_invoicing_policy",
        "alc_sale_processing_finalizer",
        "alc_stock_picking_package",
        "camptocamp_tools",  # to remove
        "connector_esb",
        "csv_file_export",  # to remove
        "csv_file_import",  # to remove
        "delivery_rounds_alcyon",
        "external_fax",
        "ir_sequence_period",
        "l10n_be_bba_fix",
        "l10n_be_vat",
        "partner_archive_new_partner",
        "product_price_import",
        "purchase_prepaid",
        "purchase_unlink_cancelop",
        "purchase_update_procurement_qty",
        "sale_quick_create",
        "server_environment_files",
        "specific_account",
        "specific_barcode",
        "specific_base",
        "specific_cutoff",
        "specific_data",
        "specific_followup",
        "specific_partner",
        "specific_print",
        "specific_product",
        "specific_purchase",
        "specific_purchase_report",
        "specific_report",
        "specific_sale",
        "specific_security",
        "specific_shipping_costs",
        "specific_stock",
        "specific_zetes",
        "speedy_views",
        "split_coda",
        "stock_inventory_controller",
        "stock_inventory_constrains",
        "stock_location_notranslate",
        "stock_location_report",
        "stock_lot_update",
        "stock_orderpoint_product",
        "stock_putaway_defaultfixedlocation",
        "stock_putaway_route",
        "stock_valuation",
        "web_autorefresh",
    ],
    "application": True,
    "data": ["security/sale_order.xml"],
    "demo": [],
}
