[outgoing_mail]
smtp_host = srv.002.ayn.grp
smtp_port = 25
smtp_encryption = none

[incoming_mail.erp]
server=srv.002.ayn.grp
port=143
type=imap
is_ssl=0
attach=1
priority=1
user=erp@ayn.grp
password=@Lcyon1590Belux
