[outgoing_mail]
smtp_host = mail.abl.grp
smtp_port = 25
smtp_encryption = none

[incoming_mail.erp]
server=mail.abl.grp
port=993
type=imap
is_ssl=1
attach=1
priority=1
user=erp@abl.grp
password=@Lcyon1590Belux

[ir.config_parameter]
ribbon.name=False
