[outgoing_mail]
smtp_host = mail.abl.grp
smtp_port = 25
smtp_encryption = none

[incoming_mail.erp]
server=mail.abl.grp
port=993
server_type=imap
is_ssl=1
attach=1
priority=1
user=erp@abl.grp
password=@Lcyon1590Belux

[ir.config_parameter]
storage.image.backend_id=alc_storage.s3_images_backend
storage.thumbnail.backend_id=alc_storage.s3_images_backend
ribbon.name=False
ir_attachment.location=db

[edi_backend_zoetis]
channel = sftp
hostname = sftp.hbsolutions.de
username = alcyonbelux
password = mGCEWxGereMPksTVxjQY
port = 22
path_read = From_PageroHBS_Prod
path_write = To_PageroHBS_Prod
pk_env_variable =

[delivery_carrier.GLS_Belgique]
prod_environment=True
gls_url=https://shipit-wbm-be01.gls-group.eu:8443/backend/rs/

[peppol_server.Edido]
url="https://api.edido.eu/peppol/send_ubl"
url_feedback="https://api.edido.eu/peppol/get_sending_status"
user=
password=

[fs_storage.fstst_eshop]
model_xmlids=

[fs_storage.fsprd_eshop]
; when changing this, also change the same parameter in the default config
model_xmlids=fs_base_multi_media.model_fs_media,fs_product_multi_media.model_fs_product_category_media,fs_product_multi_media.model_fs_product_media,fs_base_multi_image.model_fs_image,fs_product_multi_image.model_fs_product_category_image,fs_product_multi_image.model_fs_product_image,fs_product_brand_multi_image.model_fs_product_brand_image,fs_image_thumbnail.model_fs_thumbnail,alc_eshop_cms.model_alc_eshop_cms_page,alc_eshop_cms.model_alc_eshop_cms_news,alc_eshop_cms.model_alc_eshop_cms_snippet,search_engine_image_thumbnail.model_se_thumbnail,alc_eshop_ads.model_alc_eshop_ads
