# Copyright 2022 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc Purchase App",
    "description": """
        Gather all purchase related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "depends": [
        # Custom
        "acl_product_supplierinfo_import",
        "alc_additional_product_purchase",
        "alc_b2c_connector",
        "alc_incoming_product_supplier_filter",
        "alc_product_additional_price",
        "alc_product_food",
        "alc_product_last_transaction",
        "alc_product_nb_days_out_of_stock",
        "alc_product_price_import",
        "alc_product_state",
        "alc_product_supplier",
        "alc_product_supplierinfo_force_edit_form",
        "alc_purchase_announced_delivery_date",
        "alc_purchase_discount",
        "alc_purchase_incoming_products",
        "alc_purchase_order_bo_line",
        "alc_purchase_order_builder",
        "alc_purchase_order_cancel_email_template",
        "alc_purchase_order_cleaner",
        "alc_purchase_order_date_planned",
        "alc_purchase_order_readonly",
        "alc_purchase_order_rfq_filter",
        "alc_purchase_order_total_weight",
        "alc_purchase_prepaid",
        "alc_purchase_security",
        "alc_purchase_stock_orderpoint_destination",
        "alc_stock_lot_track_food",
        "alc_stock_move_line_show_quantity",
        "alc_stock_move_list",
        "alc_stock_orderpoint_product_mto",
        "alc_stock_receive_display_stock_storage_type",
        "alc_stock_receive_lot",
        "alc_stock_receive_lot_missing_product_nouveaute_info",
        "alc_stock_receive_lot_product_info",
        "alc_stock_scheduler_filter",
        "alc_supplier_purchase_manager",
        "alc_supplier_purchase_manager_account",
        # OCA
        "account_invoice_purchase_quantity",
        "partner_manual_rank",
        "product_uom_updatable",
        "purchase_cancel_reason",
        "purchase_delivery_split_date",
        "purchase_discount",
        "purchase_order_approved",
        "purchase_order_line_stock_move_cancel",
        "purchase_stock_packaging",
        "stock_orderpoint_default_location",
        # Others
        "purchase",
    ],
}
