# Copyright 2022 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc Putaway App",
    "description": """
        Gather all putaway related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "application": True,
    "depends": [
        "alc_product_package_type_tracking",
        "alc_product_packaging",
        "alc_product_packaging_dimension",
        "alc_product_dimensions",
        "alc_stock_indexes",
        "alc_stock_location_constraint",
        "alc_stock_move_group_order",
        "alc_stock_picking_zone",
        "alc_stock_scrap_responsible",
        "alc_stock_lot_unarchive",
        "alc_stock_lot_update",
        "product_abc_classification_sale_stock",
        "product_dimension",
        "product_packaging_level",
        "product_packaging_level_pallet",
        "product_route_mto",
        "stock_average_daily_sale",
        "stock_dynamic_routing",
        "stock_location_position",
        "stock_location_product_restriction",
        "stock_location_zone",
        "stock_move_auto_assign",
        "stock_picking_start",
        "stock_route_mto",
        "stock_storage_type",
        "stock_picking_start",
        "stock_storage_type_putaway_abc_classification_sale_stock",
        "stock_override_procurement",
        "alc_product_storage_temperature",
        "alc_product_dimensions_missing",
        "alc_product_barcode_required",
        "alc_reception_pharmacy",
        "alc_reception_pharmacy_printing",
        "alc_reception_pharmacy_geo_release_channel",
        "alc_stock_storage_type_sequence_condition",
        "stock_move_free_reservation_reassign",
        "procurement_auto_create_group",
        "procurement_auto_create_group_by_product",
        "alc_stock_location_putaway_rule_out",
    ],
}
