# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc Sale App",
    "description": """
        Gather all Sale related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "application": True,
    "depends": [
        # Odoo
        "sale",
        # OCA
        "base_partner_sequence",
        # OCA/sale-workflow
        "sale_triple_discount",
        "product_price_category",
        "sale_exception",
        "sale_stock_picking_blocking",
        "sale_order_line_cancel",
        "sale_route_amendment",
        # OCA/sale-channel
        "sale_channel",
        # OCA/product-attribute
        "product_manufacturer",
        "product_state",
        # OCA/odoo-pim
        "attribute_set",
        "product_attribute_set",
        # OCA/geospatial
        "base_geoengine",
        "geoengine_partner",
        "geoengine_base_geolocalize",
        # OCA/e-commerce
        "product_template_multi_link",
        # ALC
        "alc_partner_veterinary",
        "alc_product_category_data",
        "alc_product_pricelist_data",
        "alc_product_category_business_unit",
        "alc_product_category_property",
        "alc_product_lot_info",
        "alc_product_pharmacy",
        "alc_product_override_price",
        "alc_partner_pricelist",
        "alc_partner_type",
        "alc_product_supplierinfo_default_price",
        "alc_product_supplierinfo_check",
        "alc_pricelist_discount",
        "alc_sale_suite_name",
        "alc_supplier_promotion",
        "alc_supplier_promotion_sale",
        "alc_sale_order_line_cancel_check",
        "alc_sale_order_line_unavailable_list",
        "alc_sale_product_qty_backorder",
        "alc_sale_product_qty_available_to_promise",
        "alc_sale_qty_returned",
        "alc_sale_qty_returned_product_additional",
        "alc_sale_product_qty_unavailable",
        "alc_product_animal_species",
        "alc_sale_consignment",
        "alc_stock_lot_available",
        "alc_external_fax",
        "alc_sale_order_line_product_type",
        "alc_company_term_condition",
        "alc_price_triple_discount_exclusive",
        "alc_pricelist_items",
        "alc_pim_attribute_group",
        "alc_pim_product",
        "alc_sale_auto_confirm_max_delay",
        "alc_sale_channel",
        "alc_sale_internal_confirmation_mail",
        "alc_partner_manual_sale_order",
        "alc_product_web_publish",
        "alc_product_medical_device",
        "alc_product_additional_price",
        "alc_product_view",
        "alc_product_price_category_data",
        "alc_product_promoted_links",
        "alc_partner_legal_form",
        "alc_partner_pharmacist",
    ],
}
