# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Alc Sale App",
    "description": """
        Gather all Sale related modules for Alcyon""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV",
    "website": "https://acsone.eu",
    "application": True,
    "depends": [
        # Odoo
        "sale",
        "stock_dropshipping",
        # OCA
        "base_partner_sequence",
        # OCA/sale-workflow
        "sale_triple_discount",
        "product_price_category",
        "sale_exception",
        "sale_stock_picking_blocking",
        "sale_order_line_cancel",
        "sale_route_amendment",
        "sale_shipping_info_helper",
        "sale_discount_display_amount",
        "sale_product_set",
        "product_stock_state",
        "sale_wishlist",
        "product_sequence",
        # OCA/sale-channel
        "sale_channel",
        # OCA/product-attribute
        "product_manufacturer",
        "product_state",
        # OCA/odoo-pim
        "attribute_set",
        "product_attribute_set",
        # OCA/geospatial
        "base_geoengine",
        "geoengine_partner",
        "geoengine_base_geolocalize",
        # OCA/e-commerce
        "product_template_multi_link",
        # OCA/l10n-belgium
        "l10n_be_bpost_address_validation",
        "l10n_be_bpost_address_autocomplete",
        # ALC
        "alc_partner_veterinary",
        "alc_product_category_data",
        "alc_product_pricelist_data",
        "alc_product_category_business_unit",
        "alc_product_category_property",
        "alc_product_lot_info",
        "alc_product_pharmacy",
        "alc_product_override_price",
        "alc_partner_pricelist",
        "alc_partner_type",
        "alc_product_supplierinfo_default_price",
        "alc_product_supplierinfo_check",
        "alc_pricelist_discount",
        "alc_sale_suite_name",
        "alc_supplier_promotion",
        "alc_supplier_promotion_sale",
        "alc_sale_order_date_order_short",
        "alc_sale_order_line_cancel_check",
        "alc_sale_order_line_unavailable_list",
        "alc_sale_product_qty_backorder",
        "alc_sale_order_sort_by_date_order",
        "alc_sale_qty_returned",
        "alc_sale_qty_returned_product_additional",
        "alc_sale_product_qty_unavailable",
        "alc_product_animal_species",
        "alc_sale_consignment",
        "alc_stock_lot_available",
        "alc_external_fax",
        "alc_sale_order_line_product_type",
        "alc_company_term_condition",
        "alc_price_triple_discount_exclusive",
        "alc_pricelist_items",
        "alc_pim_attribute_group",
        "alc_pim_product",
        "alc_sale_auto_confirm_max_delay",
        "alc_sale_channel",
        "alc_sale_internal_confirmation_mail",
        "alc_partner_manual_sale_order",
        "alc_product_web_publish",
        "alc_product_medical_device",
        "alc_product_additional_price",
        "alc_product_view",
        "alc_product_price_category_data",
        "alc_product_promoted_links",
        "alc_partner_legal_form",
        "alc_partner_pharmacist",
        "alc_partner_sequence",
        "alc_partner_address",
        "alc_partner_suite",
        "alc_partner_call_name",
        "alc_partner_apb_authorization",
        "alc_partner_master",
        "alc_partner_manual_rank",
        "alc_sale_exception_promotion",
        "alc_sale_exception_product_category",
        "alc_sale_exception_product_availability",
        "alc_sale_statistics",
        "alc_product_shop_category",
        "alc_pricelist_role_name",
        "alc_shipping_fee",
        "alc_sales_count",
        "alc_product_newpharma",
        "alc_product_olalux",
        "alc_product_cnk",
        "alc_product_search_cnk",
        "alc_product_sku",
        "alc_sale_order_product_category_warning",
        "alc_sale_order_line_unavailable",
        "alc_sale_report_search_narcotics",
        "alc_sale_report_search_month",
        "alc_sale_order_validation_disable_tracking",
        "alc_sale_order_cancel",
        "alc_sale_product_narcotic",
        "alc_sale_product_qty_unavailable_promotion",
        "alc_sale_order_line_lots",
        "alc_sale_auto_cancel_unavailable_qty",
        "alc_sale_mto_check_procurements",
        "alc_sale_pricelist_2_menu",
        "alc_delivery_product_hide_hs_code",
        "alc_sale_order_report_customize",
        "alc_sale_order_ref_move",
        "alc_sale_security",
        "alc_product_stock_state",
        "alc_product_promotion_subscription",
        "alc_partner_category",
        "alc_product_link_notice",
        "alc_pricing_constraints",
        "alc_partner_security",
        "alc_sale_order_line_forecast_expected_date",
        "alc_customer_audit",
        "alc_product_audit",
        "alc_pim",
        "test_alc_shipping_fee_auto_process",
        "alc_product_consolidated_price_report",
        "alc_product_consolidated_price_newpharma",
        "alc_sale_order_partner_delivery_carrier",
        "alc_partner_salesperson_portal",
        "alc_partner_invoicing_mode_split_refund",
    ],
}
