from . import test_export_pharmacy
from . import test_export_product
from . import test_ws_product_stock
from . import test_ws_statistics_form
from . import test_export_stock
from . import test_xml_writer
from . import test_ws_stat_product_customer
from . import test_export_customer_address
from . import test_export_promotion_alcyon
