from ConfigParser import ConfigParser

from setuptools import setup

cfg = ConfigParser()
cfg.read('../acsoo.cfg')


setup(
    version=cfg.get('acsoo', 'series') + '.' + cfg.get('acsoo', 'version'),
    name='odoo-addons-alcyon',
    description='Alcyon Odoo Addons',
    setup_requires=['setuptools-odoo'],
    odoo_addons={'odoo_version_override': '10.0'},
    install_requires=[
        'odoo-autodiscover',
        'click-odoo-contrib',
        'odoo10-addon-account_invoice_merge_attachment',
        'odoo10-addon-product_sequence',
        'odoo10-addon-account_analytic_no_lines',
        'odoo10-addon-account_financial_report_date_range',
        'odoo10-addon-mass_editing',
        'odoo10-addon-account_invoice_force_number',
        'odoo10-addon-logging_json',
        'odoo10-addon-account_invoice_line_default_account',
        'odoo10-addon-account_invoice_merge',
        'odoo10-addon-account_invoice_tax_required',
        'odoo10-addon-account_type_menu',
        'odoo10-addon-analytic_tag_dimension_purchase_warning',
        'odoo10-addon-account_analytic_required',
        'odoo10-addon-account_mass_reconcile_partner',
        'odoo10-addon-web_sheet_full_width',
        'odoo10-addon-web_widget_many2many_tags_multi_selection',
        'odoo10-addon-analytic_tag_dimension_sale_warning',
        'odoo10-addon-stock_disable_force_availability_button',
        'odoo10-addon-web_environment_ribbon',
        'odoo10-addon-web_cache_name_get',
        'odoo10-addon-web_decimal_numpad_dot',
        'odoo10-addon-web_widget_color',
        'odoo10-addon-base_import_security_group',
        'odoo10-addon-account_payment_sale',
        'odoo10-addon-mis_builder',
        'odoo10-addon-account_banking_mandate',
        'odoo10-addon-account_invoice_merge_purchase',
        'odoo10-addon-account_cutoff_accrual_return',
        'odoo10-addon-account_invoice_accrual_merge',
        'odoo10-addon-l10n_be_eco_tax',
        'odoo10-addon-account_mass_reconcile',
        'odoo10-addon-account_invoice_payment_report',
        'odoo10-addon-account_group',
        'odoo10-addon-mail_environment',
        'odoo10-addon-sql_request_abstract',
        'odoo10-addon-account_payment_mode_auto_reconcile',
        'odoo10-addon-account_banking_sepa_direct_debit',
        'odoo10-addon-product_analytic_purchase',
        'odoo10-addon-monitoring_status',
        'odoo10-addon-base_attachment_object_storage',
        'odoo10-addon-account_invoice_split_refund',
        'odoo10-addon-l10n_be_iso20022_pain',
        'odoo10-addon-account_banking_sepa_credit_transfer',
        'odoo10-addon-server_environment_ir_config_parameter',
        'odoo10-addon-account_reconcile_restrict_partner_mismatch',
        'odoo10-addon-auto_reconcile_structured_ref',
        'odoo10-addon-account_chart_update',
        'odoo10-addon-account_move_line_report_xls',
        'odoo10-addon-mis_builder_budget',
        'odoo10-addon-account_financial_report_qweb',
        'odoo10-addon-web_export_view',
        'odoo10-addon-server_environment',
        'odoo10-addon-analytic_tag_dimension',
        'odoo10-addon-base_import_async',
        'odoo10-addon-base_technical_features',
        'odoo10-addon-l10n_be_mis_reports',
        'odoo10-addon-base_optional_quick_create',
        'odoo10-addon-sale_stock_picking_blocking',
        'odoo10-addon-purchase-delivery-split-date',
    ],
)
