from . import (
    board,
    procurement_order,
    product_category,
    product_product,
    product_template,
    stock_inventory,
    stock_location,
    stock_move,
    stock_pack_operation,
    stock_picking,
    stock_production_lot,
    stock_quant,
    stock_scrap,
)
