# -*- coding: utf-8 -*-
# Copyright 2017 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Specific ESB for Alcyon",
    "version": "10.0.2.0.1",
    "author": "Camptocamp",
    "license": "AGPL-3",
    "category": "Connector",
    "depends": [
        "alc_partner_veterinary",
        "alc_base_auto_join",
        "alc_sale_channel",
        "alc_sale_product_qty_backorder",
        "alc_sale_suite_name",
        "alc_product_dimensions",
        "alc_product_packaging",
        "alc_product_state",
        "connector",
        "delivery_rounds",
        "onchange_helper",
        "alc_pricelist_discount",
        "procurement_sale",  # TODO: partially replaced by alc_sale_product_qty_unavailable
        "product",
        "product",
        "product_dimension",
        "product_expiry",
        "product_manufacturer",
        "product_price_category",
        "purchase",
        "sale",
        "sale_delay",
        "sale_stock",
        "specific_base",
        "specific_partner",
        "specific_print",
        "specific_product",
        "specific_purchase",
        "specific_stock",
        "specific_sale",
        "stock",
        "product_additional",
        "queue_job_cron",
        "l10n_be_apb_tax",
        "delivery",
        "alc_product_category_data",
        "alc_product_pricelist_data",
    ],
    "website": "http://www.camptocamp.com",
    "data": [
        "wizards/esb_period_exporter.xml",
        "data/esb_backend.xml",
        "data/esb_backend_timestamp.xml",
        "data/product.category.csv",
        "data/product_state.xml",
        "data/res_lang.xml",
        "data/ir_cron.xml",
        "views/esb_backend_views.xml",
        "views/account_tax_views.xml",
        "views/product_views.xml",
        "views/product_uom_views.xml",
        "views/product_state_views.xml",
        "views/product_pricelist.xml",
        "views/product_category_views.xml",
        "views/res_users.xml",
        "views/res_country.xml",
        "views/res_lang_views.xml",
        "views/delivery_carrier.xml",
        "views/sale_order.xml",
        "security/ir.model.access.csv",
    ],
    "installable": False,
    "external_dependencies": {"python": ["paramiko", "simplejson", "dicttoxml"]},
}
