[outgoing_mail]
smtp_host = mailhog
smtp_port = 1025
smtp_encryption = none

[ir.config_parameter]
ribbon.name=PREPROD 1.66.6

[edi_backend_zoetis]
channel = sftp
hostname = sftp.hbsolutions.de
username = alcyonbelux
password = mGCEWxGereMPksTVxjQY
port = 22
path_read = From_PageroHBS_Test
path_write = To_PageroHBS_Test
pk_env_variable =
