from . import test_controller_sale
from . import test_export_buyx_gety
from . import test_export_customer
from . import test_export_customer_address
from . import test_export_document_zip
from . import test_export_pharmacy
from . import test_export_product
from . import test_export_product_price
from . import test_export_promotion_alcyon
from . import test_export_saleorder
from . import test_export_special_promotion
from . import test_export_stock_update
from . import test_export_stock_update_single
from . import test_export_stock_update_split
from . import test_product_supplierinfo_esbflux
from . import test_product_supplierinfo_esbflux_purge
from . import test_product_supplierinfo_esbflux_reset
from . import test_ws_create_saleorder
from . import test_ws_delivery_fee
from . import test_ws_product_stock
from . import test_ws_product_stock_cnk
from . import test_ws_product_stock_sku
from . import test_ws_saleorder_status
from . import test_ws_stat_customer
from . import test_ws_stat_product_customer
from . import test_ws_statistics_form
from . import test_xml_writer
